### ISSUE TITLE
Replace MCOs with CHL hooks

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#110]
**`XComGameState_CovertAction` -> `CI_XComGameState_CovertAction`**
* `CovertAction_ShouldBeVisible` (`ShouldBeVisible`)
* `CovertAction_CanInteract` (`CanInteract`)
* `CovertAction_ActionSelectedOverride` (~~`DisplaySelectionPrompt`~~ `
ActionSelected`)
* `CovertAction_ShouldGiveRewards` (`GiveRewards`)
* `CovertAction_RemoveEntity_ShouldEmptySlots` (`RemoveEntity`)
* `CovertAction_ModifyNarrativeParamTag` (`GetNarrative`)
* X2CommunityCore/X2WOTCCommunityHighlander#434
* X2CommunityCore/X2WOTCCommunityHighlander#383
* X2CommunityCore/X2WOTCCommunityHighlander#435

**`UIStrategyPolicy` -> `UIStrategyPolicy_CI`**
* `UIStrategyPolicy_ScreenInit` (end of `InitScreen` - UISL doesn't work as there is a frame of camera jump)
* `UIStrategyPolicy_ShowCovertActionsOnClose` (inside `CloseScreen`)

**Comment by statusNone** [comment]
created CHL issues: [#439](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/439) and [#440](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/440)
