### ISSUE TITLE
Geoscape not visible when viewing proposals after mission completion

### ISSUE THREAD

**Issue by DerRoberto** [WOTCStrategyOverhaul/CovertInfiltration#111]
After completing an activity lead mission the screen for the proposals pops up while in the Avenger, when clicking view proposals, the screen pans under the avenger where the geoscape should be.

![20190221125211_1](https://user-images.githubusercontent.com/47782227/53167610-ad681b80-35d8-11e9-833c-ea87cf20fa44.jpg)

**Comment by Xymanek** [comment]
The issue here is that you should get the popup only when you enter the geoscape, not in avenger
