### ISSUE TITLE
SitRep and Cards changes

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#126]
https://docs.google.com/spreadsheets/d/15pBV7lLXxhPUYLFL0sB9f8coERp48C5VSCRpJ4B1ark/edit#gid=0

Don't touch the mission itself yet, just implement the sitreps and have them in the random pool for starters. Mission changes will be in a different PR

Note that we will need new CA risks for the negative sitreps

**Comment by Xymanek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SitRep changes](https://trello.com/c/huvfgH4s/42-sitrep-changes)

**Comment by statusNone** [comment]
(a) remove cards which we are converting to sitreps
(b) recreate the converted cards as sitreps (i think this should be simple as they use same backend and will also teach you how sitreps wor)
(c) create new sitreps that we are adding, make them inelible for all missions in config, just usable from tql/skirmish+
(d) make new risks
(e) write new sitrep selector function for our mission sources
