### ISSUE TITLE
TLP items rework

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#130]
* Cannot be built
* 1 item given when the respective research is completed
* Weapons retain their mods, cannot be changed

**Comment by Hannibalian** [comment]
Best if the "free item" behavior is configurable as a difficulty tweak option

e.g., "GiveTLPitemOnResearchComplete=True"

Where false means you get nothing for free and have to build your items, as in the basegame

**Comment by Xymanek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TLE armors and weapons](https://trello.com/c/pADUqr36/45-tle-armors-and-weapons)
