### ISSUE TITLE
Investigate making MentalReadiness sitrep working

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#133]
Currently it's [disabled](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/f5526291b9c2377c39b78725df6e16c523c8008e/CovertInfiltration/Config/XComGameData.ini#L66). The reason is that the [current implementation](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/f5526291b9c2377c39b78725df6e16c523c8008e/CovertInfiltration/Src/CovertInfiltration/Classes/X2SitRep_InfiltrationSitRepEffects.uc#L86-L96) [grants will bonus](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/f5526291b9c2377c39b78725df6e16c523c8008e/CovertInfiltration/Src/CovertInfiltration/Classes/X2Ability_SitRepAbilitySet_CI.uc#L136) which is a great way to screw up fatigue calculation. 

We should investigate whether it's possible to make an effect that will insert a modifier into an ability hit roll, if the ability is psi (just like it's done with normal shots). Potential things to look at:

* `X2Effect_ModifyStatCheckSuccesses`
* `X2Effect_Persistent::ChangeHitResultForTarget`
* `X2Effect_Persistent::GetToHitModifiers`

**Comment by statusNone** [comment]
i remember looking into it
something about the psi ability hit roll just being a will check
psi offense vs will defense
good luck D:
