### ISSUE TITLE
Individual build "item avaliable" popup is ugly

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#158]
![unknown](https://user-images.githubusercontent.com/2865341/56474816-f2e57f80-6487-11e9-935d-0f71cfbb3bca.png)
![unknown](https://user-images.githubusercontent.com/2865341/56474821-fd077e00-6487-11e9-8c05-5635e8fd0096.png)

The issue is that the "Build items" screen uses the image stack, while the "item available" does not and just uses the base image. This issue wasn't present in vanilla as schematics didn't use stacked images at all

**Comment by cannonfodder1** [comment]
This commit has a ramshackle solution: `https://github.com/WOTCStrategyOverhaul/CovertInfiltration/commit/4c9885d39e8d01cb7d35513d6f19c3726d301d83`

**Comment by Xymanek** [comment]
"item available" code ends up [here](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/ba117b928f4acae9bac89d90da5abd3fe3d88f57/X2WOTCCommunityHighlander/Src/XComGame/Classes/UIAlert.uc#L4302-L4336) which supports only 1 image, which makes me believe that flash also doesn't support image stack.

A potential solution would be UISL which will just spawn base attachment images on top of actual one

**Comment by cannonfodder1** [comment]
But then they would still look all light blue, which while better than being broken is still not ideal

**Comment by Xymanek** [comment]
Initial work in 3350ee075c2161ab30b278cf6a17c5dd020e2417 but the image isn't sized correctly: 
![unknown](https://user-images.githubusercontent.com/2865341/56634562-1ae10880-666b-11e9-9d3b-f2cd5f3e6ea8.png)

Need to try calling the entire flash func and seeing if that works properly

**Comment by Xymanek** [comment]
Fixed in b008d77d7e29c6d4dabd5a90406b4f962ef7ec84
