### ISSUE TITLE
Improve logic for picking location/faction of P1s

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#162]
Original idea:

1. Get a random contacted region that has the least infiltrations right now
2. Get a faction that controls that region
3. If said faction isn't met pick one that has the least infiltrations currently

Considering the ideas to include normal CAs into mission chains, it may be prudent to check for active mission chains, not only infiltrations (but then we need a way to track mission chain as whole)

**Comment by cannonfodder1** [comment]
Do factions have territory other than their HQs? I think only the Chosen have territory. We could just map the Chosen's rival faction to their territory as a workaround though.

**Comment by Xymanek** [comment]
Yeah, all regions are are assigned to a faction I'm sure

**Comment by Xymanek** [comment]
Not relevant anymore
