### ISSUE TITLE
Expanded event queue is backwards

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#17]
![image](https://user-images.githubusercontent.com/2865341/47996695-11d29e00-e102-11e8-8467-d4eb647c311d.png)

Also happens on map

**Comment by cannonfodder1** [comment]
What exactly is the problem? That event queue looks correctly ordered to me.

**Comment by Xymanek** [comment]
Ooops. I was under the impression that the nearest upcoming thing is at the bottom (probably confused by vanilla sticking covert op always at the bottom).

P.S. I'm going crazy from the amount of time I spend on this project....
