### ISSUE TITLE
Dark Events become active with no chance to counter them

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#185]
In my run, the first Dark Event became active without there ever being a chance to counter it. 

The next month, I got two infiltration missions of the type Counter Dark Event. While infiltrating both of these missions, the next Dark Event became active, again with no chance to counter it. Also, while selecting the Counter Dark Event Mission, the player can not see which Dark Event they are countering.

**Comment by Xymanek** [comment]
Note to whoever will work on this: we first need to implement the full chains system (#174) before addressing this issue
