### ISSUE TITLE
No additional information about the risks in Covert Op selection window

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#187]
Unless you know exactly what each risk does, you can't make an informed decision about e.g. which soldiers to bring in order to deal with said risk(s). Ideally, hovering over the risks section would provide more detailed information about them.

**Comment by Xymanek** [comment]
Things to consider:

* `X2CovertActionRiskTemplate`s do not have a `localized` field for description
* Controller support

**Comment by Xymanek** [comment]
Handle this by checking if the risk is a flat risk. If so, fetch the associated sitrep and use its description

**Comment by statusNone** [comment]
seems like the system that staples risks onto the missions is not completed? i think this is needed to work on this issue..

**Comment by Xymanek** [comment]
It is completed. Ping me in discord if you are lost

**Comment by Xymanek** [comment]
Need to wait for #237 as that will potentially change how the risks are displayed

**Comment by bstar1million** [comment]
Should ideally work in both Covert Action screen and loadout screen.

**Comment by Xymanek** [comment]
The biggest hurdle with this is controller support tbh
