### ISSUE TITLE
Duplicated Recruit Faction Hero CAs

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#188]
This happened with the Templars as the starting faction. Currently, the Recruit Templar Covert Op is available 4x.

**Comment by Xymanek** [comment]
* Screenshot please
* What other mods do you have that may affect this?

**Comment by bstar1million** [comment]
> What other mods do you have that may affect this?
None as far as I can tell.

**Comment by Xymanek** [comment]
Will need the full modlist then, as CI isn't supposed to touch those CAs at all

**Comment by bstar1million** [comment]
Full mod list, at the risk of being strangled for using this mess for testing (but hey, at least there are categories!):

https://pastebin.com/vm7GWEQY

**Comment by Xymanek** [comment]
"Always Recruit and Rescue" is probably the interesting one here

**Comment by bstar1million** [comment]
![after_console_command](https://user-images.githubusercontent.com/44277211/57582002-f0db7300-74bf-11e9-88bc-54cdbe290528.png)
![Uploading before_console_command.png…]()

**Comment by bstar1million** [comment]
![after_console_command](https://user-images.githubusercontent.com/44277211/57582029-36983b80-74c0-11e9-817f-265e875658cf.png)
![before_console_command](https://user-images.githubusercontent.com/44277211/57582030-3730d200-74c0-11e9-9cc8-4baa0a3d2253.png)

**Comment by Xymanek** [comment]
Attach a save as week if it doesn't help

**Comment by bstar1million** [comment]
Config reset didn't help.

[save_Save 43.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/3170063/save_Save.43.zip)
[stratoverhaul_alpha2_RPGO.txt](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/3170064/stratoverhaul_alpha2_RPGO.txt)
Savegame & AML mod list

**Comment by Xymanek** [comment]
@statusNone @ArcaneData1 any of you want to take a crack at this with the debugger? 

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/eea83c61b9d48271b36868cda941595df0261a67/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_ResistanceFaction.uc#L727-L728 is the area of interest

**Comment by statusNone** [comment]
i'll take a look at it

**Comment by statusNone** [comment]
you assumption was correct xy the offending mod is "Always recruit and rescue"

**Comment by Xymanek** [comment]
That mod used to work fine for me (before starting CI development). Could you try it with only our CHL? I have a suspicion that we fixed a bug it relied on

**Comment by Xymanek** [comment]
I'll leave the issue open just so that we don't forget about this - this shouldn't be an incompatibility
