### ISSUE TITLE
Mental Readiness should show the precise bonus

### ISSUE THREAD

**Issue by Samio321** [WOTCStrategyOverhaul/CovertInfiltration#193]
In keeping with the theme of OverInfil bonuses being explained exactly, **it'd be great to have an exact readout of its bonus with the % increase/decrease included with the Mental Readiness sitrep.** Information should be freely given in detail about game mechanics in general.

**Comment by Xymanek** [comment]
@statusNone @ArcaneData1 can one of you do this?

**Comment by Xymanek** [comment]
Implemented in #217
