### ISSUE TITLE
Risky CAs to include rescue/datatap missions

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#196]
The rescue guerilla ops in Abandoned Cities are currently not represented, and the Protect Datatap guerilla op does not fit as a infiltration mission.

Suggestion: Covert actions that have an above-average reward of supplies/intel, but have a chance for the operation to be compromised afterwards, spawning an instant non-infiltrated mission.
In the case of a datatap you would try to save the intel reward.
For the rescues we have two options:
- The rescue targets are the squad sent to the CA. If you rescue them you also recover some to all of the supplies. If you dont rescue them they return wounded and shaken.
- The rescue targets stay random resistance and you recruit them afterwards, as a compensation for losing the original reward and for the effort.

The CA with the Protect Datatap risk could also have an alternate version that counters a dark event instead, but that one should have a higher chance to go wrong and some rank prerequirements.

*Transferred from trello during reorganization. Originally by @ChrisTheThinMint*

Probably need to wait for #174

**Comment by cannonfodder1** [comment]
Option 1 would require some mission type editing, and there's also the problem that the in-danger squad is sent back to the Avenger on the Skyranger after their first mission. I think we should go with Option 2. The squad flies back to the Avenger on the Skyranger, but the spoils from their mission are transported by resistance personnel on foot back to a Haven. I think this balances out thematic sense and technical effort the best.
