### ISSUE TITLE
Make covert actions use normal ordering in the event queue

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#2]
The code that forces covert actions to be always shown seems to be this: https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/84e168b5da6d5414b466cf3a54ed4be657257ded/CovertInfiltration/Src/CovertInfiltration/Classes/UIEventQueue_MultipleActions.uc#L49-L133

**Comment by cannonfodder1** [comment]
I've poked around a bit, conclusions:
1. Nuking the entire thing removes ALL events from the event queue
2. Using selective removal of lines related to covert actions results in only a single CA event at once

With these in mind, it would seem that the highlighted code is downright essential for multiple CAs at once, and overrides the base-game event queue code, and thus cannot be blanket nuked. Tomorrow I'm going to pick it apart line by line and figure out exactly what must be changed and what must be preserved.

**Comment by cannonfodder1** [comment]
Successfully rewrote UIEventQueue_MultipleActions.uc to allow CA events to be hidden behind the "expand event queue" button and be sorted with normal events based on time remaining.
![20181005200511_1](https://user-images.githubusercontent.com/1369684/46566815-98fddd80-c8da-11e8-8092-4830f01b0e06.jpg)
