### ISSUE TITLE
Remove overpowered POIs

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#201]
Definitely the Engineer and Scientist POIs should be cut, perhaps the Assorted Loot (ammo or grenade) as well

*Transferred from trello during reorganization, originally by @cannonfodder1*

**Comment by ChrisTheThinMint** [comment]
Kinda worried that PoI variety suffers if we cut too many. Consider nerfs instead. Engineer and Scientist PoIs could unlock infils instead.

**Comment by Xymanek** [comment]
> could unlock infil missions

This might be an issue if the player is stretched on people and doesn't get a choice of POIs. Maybe spawn multiple POIs each time in this case?

**Comment by ChrisTheThinMint** [comment]
Or maybe make the expiration timer on the PoI-spawned mission lenient. Something like 20 days.

**Comment by Thrawn007** [comment]
POI's can also be balanced other ways.

1) Scan time -  If an Engineer takes 20 days, and I know I could get 3 to 4 other POI's in that time, its a harder decision than if it's 1 to 1.

2) Rarity - making sure more valuable POI's don't show up as often can balance things simply by requiring you to be lucky.

3) Unlocks - POI's can be "locked" so they don't show up until after a certain event.  This could simply be after a certain date or at a certain force level, but also could be not going into the pool until a certain event takes place.  This could make some POI's have plot flavor to them by fitting in with other things that have happened such as a certain Chosen or Ruler showing up in a mission, unlocking a faction, or finishing a certain kind of mission.

**Comment by Xymanek** [comment]
Closed by #335
