### ISSUE TITLE
Reward window in Covert Ops screen doesn't scroll text

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#204]
Longer loc texts that exceed the size of the window can't be read completely. See screenshot.

**Comment by bstar1million** [comment]
![rewards](https://user-images.githubusercontent.com/44277211/57893245-7bb2c980-7842-11e9-9fa6-dbdfd65b6aa7.png)

**Comment by Xymanek** [comment]
@statusNone this one is for you, since you messed with that screen already - take a look at how the top center text box works, it implements the scrolling

@bstar1million why are the `INTEL` and `SUPPLIES` labels top right yellow?

**Comment by bstar1million** [comment]
@Xymanek  I think it's this mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1641846474
