### ISSUE TITLE
Should we implement squad UI?

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#205]
While we are not averse to the idea, so far the consensus was generally being shifted towards "no squad mechanics - no squad UI". Furthermore, the next mod we are planning to make is squads overhaul, so it makes sense to wait for that and not have competing UIs.

On the other hand, it's regularly brought up on discord that people have issues managing larger roster without such utility.

Creating this thread to facilitate collection of arguments for and against as spontaneous discord discussions keep getting lost

**Comment by Dustin1230** [comment]
It really depends on what you want to get into with the Squads Overhaul.  If you have plans to work towards a more coherent Squad UI at a later time then throwing something together now might lead to putting off a more well developed version later.

**Comment by Xymanek** [comment]
Not going to be implemented for CI workshop release
