### ISSUE TITLE
Build a deck system for Mission Chains

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#208]
Use a deck system for mission chains just like vanilla GOp rewards. This would prevent two identical mission chains from showing up in the same month and give some structure to the randomness. We could vary what's in the deck by month to solve the issue of first month randomness.

For example, the first month's deck could be Recruit Engineer, Gather Intel, and Retaliation. That's four missions in all, with three entry points. The entry points would be spread out over the month. Then the second month's deck would include Recruit Scientist, Supply Raid, and Counter Dark Event.

After the first few months we can move to a generalized deck containing one of each of the valid chains at the moment, which doesn't reset every month but rather gets regenerated when every chain is spawned.

**Comment by Xymanek** [comment]
> Retaliation

Retals are currently using vanilla's schedule

I'm not really find of using vanilla's approach tbh. I would rather prefer a mix of #209 and some sort of mid-month timed popups

**Comment by cannonfodder1** [comment]
We could keep the "Weeks Until Retal" timer, but when the timer is up a Retal gets added to the deck

**Comment by Xymanek** [comment]
Meh, leave retals alone for now
