### ISSUE TITLE
Midgame option to start Mission Chains of the player's choosing

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#209]
We may want to include some system by which the player can take the initiative to start new chains on their own. This could take the form of new preparation CAs, or maybe spending intel to "purchase" a chain. Feedback and ideas needed.

**Comment by Xymanek** [comment]
One of my ideas was to spawn a couple infil CAs as part of the monthly rotation. If the player sends someone there then the chain goes on normally. If they ignore it, then it simply dissappears at the end of the month

**Comment by ChrisTheThinMint** [comment]
My suggestion would be to use datapad research for this. Introduce 3-5 research projects that require a datatap and unlock a mission chain when completed. Could either replace normal datapad research and give a small intel reward with each project, or keep it around for the tradeoff.

**Comment by Xymanek** [comment]
@cannonfodder1 do we still want this even with all the latest changes?

**Comment by cannonfodder1** [comment]
I don't think this issue has any relevance in the current iteration of CI.
