### ISSUE TITLE
Allow infiltrations to have more than one risk

### ISSUE THREAD

**Issue by ChrisTheThinMint** [WOTCStrategyOverhaul/CovertInfiltration#233]
Change infiltration missions to be able to have and display more than 1 risk, and create UI to let the player decide which risk should be removed once an infiltration hits that tier. If no risk is removed, the mission will have all risks(!), instead of rolling one randomly like previously suggested. 

This feature could be used on high alert missions in general, giving them a chance to have an extra risk to force the player to choose between two evils, and also opens up a way to increase the difficulty of specific infiltration missions.

**Comment by Xymanek** [comment]
> If no risk is removed

Could you clarify this case? I.e. When would such thing happen?

**Comment by ChrisTheThinMint** [comment]
> 
> 
> > If no risk is removed
> 
> Could you clarify this case? I.e. When would such thing happen?
When you dont get the overinfiltration bonus that removes a risk. 

The last suggestion for the system was that you would only roll one of the risks, and im trying to clarify that my suggestion is that you get all of them on the mission.

**Comment by cannonfodder1** [comment]
> let the player decide which risk should be removed
The original idea was to have two potential risks, then one would trigger on a 50/50 chance for either or, without any player input. How would player choice in this particular instance work thematically and improve the game mechanically?

**Comment by Xymanek** [comment]
@ChrisTheThinMint so do you mean to have the mission launch with 2 (if no removal bonus) or 1 (if got removal bonus) risks?

**Comment by Thrawn007** [comment]
Want to clarify a few things, since I've been out of the loop a while:
1) Assuming the risk list is still capture/wounded/ambush or is there more variations?
2) Assuming multiple risks happen, what is the order of operations?  
   2a) Will there be a set of operations such as capture a soldier, then wound a soldier, then run ambush scenario?
   2b) Will there be a random order, so we need to figure out each case.  (Such as if you get wound before capture, can the wounded soldier be the captured soldier, or does it automatically look for another soldier.  Or if you get ambush before capture, would that mean running the scenario, and then finding someone got nabbed on the way out?)

**Comment by Xymanek** [comment]
You are really out of the loop :)
Come on discord to catch up

**Comment by ChrisTheThinMint** [comment]
> @ChrisTheThinMint so do you mean to have the mission launch with 2 (if no removal bonus) or 1 (if got removal bonus) risks?
Yes.

> The original idea was to have two potential risks, then one would trigger on a 50/50 chance for either or, without any player input. How would player choice in this particular instance work thematically and improve the game mechanically?

First, thanks for clearing that suggestion up, it wasnt really documented anywhere and we weren't sure what it was about. To answer your question: 

Thematically, i see risks more as something permanent happening on the mission site, so i dont think it makes sense for only one of the two circumstances to actually happen by chance. Also, it would be pretty easy for observers to figure out these security measures, so with enough preparation our squads can disable or avoid a specific one.

Mechanically, it gives the player more agency while also making the risk removal bonus more desirable for these high risk missions. Also keep in mind that my suggestion revolves around only giving some missions more risks, not all of them. The two risks are supposed to present a significant combined threat because single risks start being more irrelevant and easy to counter with later squads.

**Comment by cannonfodder1** [comment]
This was an interesting idea, but the design of the overinfiltration system is pretty much locked in for final release at this point, and I think it is perfectly fine as-is.
