### ISSUE TITLE
Create Barracks Size Limiter

### ISSUE THREAD

**Issue by lago508** [WOTCStrategyOverhaul/CovertInfiltration#236]
Being able to attempt multiple missions encourages maintaining a huge barracks instead of choosing missions.

To counter this, the Avenger has a Crew Limit. Soldiers, Scientists and Engineers count as crew.
For each crew member over X, all recovery times are increased by +10%.

Crew Size/Crew Limit is displayed on the top bar (with supplies, scientists and engineers).
Crew Limit can be increased by purchasing upgrades at the Crew Quarters or Bar.

**Comment by Thrawn007** [comment]
Possible additions:
1) Inspired technology (improved comforts?) to either increase crew limit or reduce penalty by 5%
2) Dark Event (supply shortage) that increases penalty by 10% (or more?)
3) Talent (Scavenger? Survivalist?) that makes a soldier not count against the crew limit?

**Comment by Xymanek** [comment]
> Scientists and Engineers count as crew

What about Bradford, Commander, Tygan and Shen?

**Comment by Thrawn007** [comment]
I'd consider them already build in, so that nobody has to track them.

**Comment by lago508** [comment]
Including them is just reducing the cap by 3.

I'd keep it simple and stick with Soldiers + Engineers + Scientists. Including Shen, Tygan and the Clerks is unnecessary complication in my opinion.

**Comment by Xymanek** [comment]
> Crew Limit can be increased by purchasing upgrades at the Crew Quarters or Bar

Let's do Crew Quarters as 

1. That's where you can get a list of all staff
2. There is a mod already that adds things to the bar

**Comment by Xymanek** [comment]
I think it makes sense for this to be facility upgrades because

1) Fits narratively
2) PG is already overcrowded from various mods and we want the player to reliably be able to purchases these upgrades
