### ISSUE TITLE
"Blank" Infiltration Mission ending up in a missing squad

### ISSUE THREAD

**Issue by 1captainKek** [WOTCStrategyOverhaul/CovertInfiltration#240]
![XCom2 2019-08-22 01-18-14](https://user-images.githubusercontent.com/54402022/63512070-d8acc400-c4b0-11e9-91a9-c944d88ea5df.png)

re the above picture: embarking on this mission w/ a squad ends up with the infiltration timer reading 100 (0% max) and the game forces you to take the mission, much like a 200% infiltrated mission. 

Upon loading, there are no soldiers in the avenger or in the room part of the loading screen. THe mission starts and there are no soldiers on the field. 

Upon completing the mission, the soldiers that were supposed to have been on that mission are still listed as "0" in the Barracks status column.

**Comment by Xymanek** [comment]
Can you attach the save file?

**Comment by 1captainKek** [comment]
https://drive.google.com/file/d/1HgwzbD-c50CrMQCsxiH4M68eitStWX3L/view?usp=sharing

Please see above

**Comment by Xymanek** [comment]
Ok, so I took a look and indeed it seems like this infiltration is missing a bunch of setup. @cannonfodder1 

1) Fix this: https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/6210568292846d36b5e0c6918f4dad33dcb6cfe9/CovertInfiltration/Localization/XComGame.int#L112-L125
2) Add an image entry for it (`XComGameBoard.ini`)

**Comment by 1captainKek** [comment]
Found a second mission with the same issue, not sure if it's the same mission type. Attaching the save file here.

https://drive.google.com/file/d/16Dd_NoBnisNJ1DLjXv4JxZTGZcckh99a/view?usp=sharing
