### ISSUE TITLE
Issue before lauching a mission after an Infiltration

### ISSUE THREAD

**Issue by jagonchen** [WOTCStrategyOverhaul/CovertInfiltration#241]
**Unable to launch mission, squat is "grayed out" in barracks, squat preview is empty and there are not other missions infiltrating.**

https://cdn.discordapp.com/attachments/496726597844467713/615070141176086528/save_AUTOSAVE-_Campaign_27_Mission_2

![1](https://user-images.githubusercontent.com/5413288/63716056-5995f380-c802-11e9-87ac-ea0d2af98d55.png)
![2](https://user-images.githubusercontent.com/5413288/63716069-5bf84d80-c802-11e9-97a0-63d91c2d1e9e.png)
![3](https://user-images.githubusercontent.com/5413288/63716075-5dc21100-c802-11e9-98d5-17478097eb75.png)
![4](https://user-images.githubusercontent.com/5413288/63716078-5f8bd480-c802-11e9-84d1-b2cdc50ce055.png)

**Comment by Xymanek** [comment]
Need the mod list for this save, the one you posted in discord appears to be different

**Comment by Xymanek** [comment]
Closing because unable to replicate or load the save (no mod list)
