### ISSUE TITLE
Add the ability to create new risks from config

### ISSUE THREAD

**Issue by 1captainKek** [WOTCStrategyOverhaul/CovertInfiltration#242]
In the interest of opening the config to incorporating third party mods (ie raider factions, MOCX) into infiltrations, this would allow an advanced user to modify his own files according to his own game configuration.

**Comment by Xymanek** [comment]
The current implementation already supports this, just need to document it

**Comment by Xymanek** [comment]
Done: https://github.com/WOTCStrategyOverhaul/CovertInfiltration/wiki/Custom-infiltration-risks
