### ISSUE TITLE
Empty mission rewards UI spots

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#254]
As most logic is now handled by the chain itself, there are no rewards attached to the missions. That does, however, leave the UI spots empty and we should address that. Possibly:

* Create dummy loc-only rewards
* Use the activity proxying approach

**Comment by Xymanek** [comment]
This is def being blocked by #257

**Comment by cannonfodder1** [comment]
Partially fixed by #297, commit incoming to fix the rest
