### ISSUE TITLE
Gatecrasher too easy/additional enemies not showing up (?)

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#262]
Difficulty: Commander
Number of enemies: 8
Faction hero: Templar
Mod list: attached (barebones, RPGO & CI, 8 mods)

Mission felt way too easy, even for commander. Definitely needs to be more difficult. Seems like CI's additional enemies are not spawning?

**Comment by bstar1million** [comment]
[CI_RPGO_base_list.txt](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/3686298/CI_RPGO_base_list.txt)

**Comment by Xymanek** [comment]
Current config:

Difficulty | Alert level
--------- | ----------
0 | 2
1 | 3
2 | 3
3 | 4

Alert level | Pod count | Enemy count
---------- | ---------- | -------------
1 | 2 | 5
2 | 2 | 6
3 | 3 | 8
4 | 4 | 11

For vanilla values, reduce alert level for each difficulty by 1

**Comment by Xymanek** [comment]
Ok, so I played the mission a couple of times and I think replacing the 3 troopers pod with officer+2 troopers will be a good compromise here. Not sure if legend needs to be changed, it's pretty hard already

**Comment by Xymanek** [comment]
Discord decision: switch one of the 3 trooper pods to officer pod on both commander and legend

**Comment by Xymanek** [comment]
Fixed in 517280d5128ed27b589f7a774a80abc20a1c4f47
