### ISSUE TITLE
Tutorial pop-up window "Infiltration" difficult to read

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#263]
The "Infiltration" tutorial window has quite a wall of text dense in information that immediately starts autoscrolling. Could that window have a manual scroll bar instead?

**Comment by Xymanek** [comment]
This will be an annoying one to change, that popup is entirely in flash.

@cannonfodder1 didn't you plan to condense the text in tutorial popups?

**Comment by cannonfodder1** [comment]
I've tried my best in #261 but there's a lot of information that's pretty essential.

**Comment by Xymanek** [comment]
Closed in favour of #349
