### ISSUE TITLE
View chain not noticeable enough

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#264]
Blue outline + text colour of "View chain" button doesn't stand out enough from the blue-ish continents and blue ocean of the geoscape in the background. 

I think bright green that's used for other buttons would work better.

**Comment by Xymanek** [comment]
Seemed pretty noticeable to me. Maybe it's a specific circumstance, provide a screenshot?

Also note that the button turns red when there is a complication on the chain

**Comment by cannonfodder1** [comment]
Is this still relevant with the new UI elements that have replaced the View Chain button?

**Comment by Xymanek** [comment]
No, it isn't
