### ISSUE TITLE
Assault mission doesn't have localization/info

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#266]
In the chain UI, Assault has no localization at all.
The geoscape mission launch screen has no info on the mission's reward and no image.

![assault_loc](https://user-images.githubusercontent.com/44277211/66136017-14cc5c00-e5fb-11e9-9cda-020531f58167.png)
![assault_loc2](https://user-images.githubusercontent.com/44277211/66136023-1564f280-e5fb-11e9-8472-b9ffd6fcabd7.png)

**Comment by Xymanek** [comment]
This is `ActivityChain_IntelIntercept`. The resource container is empty, hence empty description in reward field. See #267 for details
