### ISSUE TITLE
Chain ends without chance to attempt second mission

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#267]
I either never got a chance to attempt the second step in the chain or it completely slipped by unnoticed ... which I think is unlikely since I was specifically paying attention to all my infils and missions.

![chain_ended](https://user-images.githubusercontent.com/44277211/66136308-8906ff80-e5fb-11e9-8481-2dd7b34a6cb6.png)

[save_CI_test_bstar1.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/3686596/save_CI_test_bstar1.zip)

**Comment by Xymanek** [comment]
Time at strategy load: 58633 14/03/2035
Mission expired: 47842 15/03/2053
Geoscape paused: 48235 15/03/2035

Then the intel intercept mission was spawned (bug, shouldn't happen when the last activity in complicated chain wasn't successful at least partially). The player looked at the mission multiple times and it still remains on Geoscape. 

I see no reason to believe that the 2nd stage mission wasn't available. @cannonfodder1 is the 1 day timer excepted though?

**Comment by Xymanek** [comment]
Note to self: write a command to `ObliterateGameStatesFromHistory` to 5478 (last state before entering geoscape) to check what exactly the player experienced

**Comment by Xymanek** [comment]
Ok, so after reverting the save, I can see that while the mission has spawned (and you could go on it), the notification didn't trigger which explains why you missed it

Technical: listener registration for `ActivitySetupComplete` on `XCGS_Activity` was lost in strategy->tactical->strategy transition
