### ISSUE TITLE
Sync colors for Squad Select notes and CA screen

### ISSUE THREAD

**Issue by robojumper** [WOTCStrategyOverhaul/CovertInfiltration#27]
The CA screen and the squad select notes have a bunch of different colors for the same information. We need to decide on the color for the notes and make the colors on the CA screen match.

**Comment by Xymanek** [comment]
I agree. I also think that it might a good idea to extract the colour settings into `XComUI.ini`.

One potential problem though: `UIUtilities_Strategy::GetStrategyCostString` (which is used to show the optional resource costs such as "25 supplies") already colours each entry green/red depending on whether the player can afford it. We might need to replicate that function if we want to change the colouring logic

**Comment by Xymanek** [comment]
Closing as this was created eons ago when the world was young an naive
