### ISSUE TITLE
No "Infiltrating" status displayed in soldier list when deploying for normal CA

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#279]
![CA_status](https://user-images.githubusercontent.com/44277211/66257729-01f18d00-e79d-11e9-8776-6562ddd15149.png)

**Comment by Xymanek** [comment]
Incompatibility with DSL as the latter doesn't implement the required CHL feature.

I'll leave this open as a reminder for myself to bug bountygiver

**Comment by Xymanek** [comment]
DSL PR with everything that we need: https://github.com/bountygiver/DetailedSoldierListWOTC/pull/5

**Comment by Xymanek** [comment]
DSL PR was merged
