### ISSUE TITLE
Dark Event name in Chain UI easy to miss

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#281]
I suggest leaving out the rest of the sentence "Resistance heard about..." and use only the DE's name and possibly highlight it in a different colour, e.g. red.

Also: Make description multi-line text instead of scrolling line.

**Comment by Xymanek** [comment]
> Make description multi-line text instead of scrolling line

This needs to be implemented by me. #297 Fixes the rest
