### ISSUE TITLE
Chain UI: Current step could have clearer status(es)

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#283]
Instead of "Not completed yet", I suggest distinguishing between:
- Available (or some other synonym)
- In Progress / Infiltrating

This will make it easier for the player to know if they need to take action, i.e. deploy a squad.

**Comment by Xymanek** [comment]
Ugh... The activity system is very generic...

But I guess you are right

**Comment by Xymanek** [comment]
To be implemented after #297 is merged

**Comment by Xymanek** [comment]
![image](https://user-images.githubusercontent.com/2865341/66653840-93e81280-ec41-11e9-8e96-f9d97dd5187a.png)
![image](https://user-images.githubusercontent.com/2865341/66653846-98143000-ec41-11e9-9133-3242265dfa92.png)
![image](https://user-images.githubusercontent.com/2865341/66653955-d1e53680-ec41-11e9-833d-833aaa013629.png)
![image](https://user-images.githubusercontent.com/2865341/66653966-d873ae00-ec41-11e9-8cc6-82dbcfb2fcad.png)

I'm not sure if "Ongoing" should be replaced with "In progress", but anyone can edit the loc - it's here: 

https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/5ecf1a4d6085d20728b8537233aeb34dae5cbf4c/CovertInfiltration/Localization/CovertInfiltration.int#L97
