### ISSUE TITLE
Infiltration Size I+II both require Captain rank

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#285]
According to NotSoLoneWolf this is not intended and code says rank 3+5 respectively. Attached screenshot and save.
[save_CI_test_bstar2.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/3693836/save_CI_test_bstar2.zip)
[CI_PCP_base_list_UI.txt](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/3693837/CI_PCP_base_list_UI.txt)
![GTS](https://user-images.githubusercontent.com/44277211/66262538-a813b600-e7e2-11e9-9c45-65008f07145b.png)

**Comment by Xymanek** [comment]
The issue is that the higher requirement was set for legend difficulty, not for 2nd unlock

https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/4da2c2f19909e58bc9175c23a04cd8b43518f80c/CovertInfiltration/Config/XComStrategyTuning.ini#L312-L326
