### ISSUE TITLE
Improve barracks status readout

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#293]
![image](https://user-images.githubusercontent.com/2865341/66291863-8520f900-e8eb-11e9-9f43-732b81a9f490.png)

* Add tired as separate entry from available (rename latter to ready)
* Split unavailable to "On CAs", "Infiltrating" and "Unavailable"

**Comment by statusNone** [comment]
screen listener or chl hook?

**Comment by Xymanek** [comment]
Neither, it's a delegate on the facility template
