### ISSUE TITLE
Chains: Next step not triggering/spawning

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#295]
(1) **Destroy Facility**: Covert Action "Investigate the possibility of a raid on AVATAR project facility": Success.
Next step would be an Infiltration "Neutralize Advent VIP". That doesn't trigger/spawn though.

(2) **Seize ADVENT VIP**: Infiltration "Recover valuable piece of information...": Success. 
Next step would be an Infiltration "Neutralize Advent VIP" doesn't trigger either. 

Not sure if I'm missing something here - do I need to research the Facility lead? Have I already completed the missions and the chain just hasn't updated? I'm very confused.

![chains_1](https://user-images.githubusercontent.com/44277211/66353450-5a25bc00-e962-11e9-8cd7-262ad4fccffb.png)
![chains_2](https://user-images.githubusercontent.com/44277211/66353452-5bef7f80-e962-11e9-9a5d-a812f4aed8cd.png)

[CI_test_PCP_bstar2.txt](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/3699851/CI_test_PCP_bstar2.txt)
[save_CI_test_bstar3.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/3699855/save_CI_test_bstar3.zip)

**Comment by Xymanek** [comment]
Was the campaign started before or after 4.1?

**Comment by bstar1million** [comment]
After 4.1

**Comment by Xymanek** [comment]
The infiltration missions/CAs states indeed were not created themselves, although the chain state code has marked that it reached this stage (which means that the code for infiltration creation should've been invoked). I have no idea how this could've happened and the history inside the save file only goes back to "after action" screen for retaliation mission, which also doesn't help.

I'm closing this issue as there isn't any way to debug this... If this happens again, please open a new issue
