### ISSUE TITLE
TLP weapons don't have attachments

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#296]
They're supposed to have their default attachments, but in CI they don't.

**Comment by Xymanek** [comment]
Since v1.19 CHL update has hit the workshop, people are reporting the same issue. Since CI's CHL always had that CHL version "integrated", it's possible that the issue is there

**Comment by Xymanek** [comment]
CHL issue: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/657
