### ISSUE TITLE
Make Vulture a GTS perk again

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#299]
The increased size of the active roster means that loot/upgrades are spread very thin. If you want to have any hope of equipping your whole squad, you need increased loot drops. 

This makes Vulture more of a mandatory perk. Resistance cards should be optional since there's now way to guarantee that you get them.

**Comment by Xymanek** [comment]
I think a better approach is to make it a lvl 0 card (guaranteed)

**Comment by Xymanek** [comment]
I think we bump up the number of loot drops per mission. In vanilla it's quite often that you can't pick up the loot (cuz combat) but this way player is certain to collect more loot

**Comment by Xymanek** [comment]
Decision: for Beta 1, bump up the Timed Loot Per Mission in GameData.ini from 1 to 4 (LW2 had 5, but they also had more enemies). I think that will suffice

**Comment by Xymanek** [comment]
Decision: for Beta 1, bump up the Timed Loot Per Mission in GameData.ini from 1 to 4 (LW2 had 5, but they also had more enemies). I think that will suffice
