### ISSUE TITLE
Remove "Between the eyes" card

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#306]
1) It's ridiculously stupid
2) There are much less mission with The Lost in CI, so it's effect is rarely noticed

**Comment by cannonfodder1** [comment]
CI does make it much less OP though because of the rarity of the Lost, so I'm not sure it needs to be removed

**Comment by Xymanek** [comment]
I think many people would waste a slot with it, thinking that it's as good as in vanilla

**Comment by Xymanek** [comment]
Since lost are now more common with #405, my argument above no longer stands
