### ISSUE TITLE
Class based TLE Armors at Plated and Powered tiers are buildable

### ISSUE THREAD

**Issue by MrCloista** [WOTCStrategyOverhaul/CovertInfiltration#307]
Class based TLE Armors at Plated and Powered tiers are buildable. They have identical stats to the 'prototype' given by the research, but are class locked and also have an invisible torso mesh for both genders.

**Comment by cannonfodder1** [comment]
Closed with commit 8776e1a56e3823d09ff5075225be6cad9ed03849
