### ISSUE TITLE
Hide retal timer from DE screen

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#320]
Too meta

**Comment by cannonfodder1** [comment]
I disagree, this smacks of the LW2 sentiment of hiding information from the player. That doesn’t go over well.

**Comment by cannonfodder1** [comment]
Maybe change it so it tracks by month instead of by week? IE if it’s 3 weeks or more then the screen says Retaliation Preparing and of its sub 3 weeks then the screen reads Retaliation Imminent. 

But that’s still taking away information. Why do you believe the tracker is a problem?

**Comment by ansabalirai** [comment]
I imagine it is because you can easily over extend your barracks knowing you still have time for handling a retal and "game" the CI system in general

**Comment by cannonfodder1** [comment]
In LW2, you couldn't see Vigilance levels, which were vital to predicting the movement of ADVENT legions around the strategy map. People absolutely hated this and one of the most popular mods for LW2 is a UI mod to put Vigilance levels in the game where the player could see them. This allowed people to "game the system" somewhat but it's still one of the most enduring tweaks to LW2 that you see on practically every campaign on youtube with the exception of those that started in the week or so before the mod was released.

My point is, this is a double edged sword, but I think concealing information is going to bite us far more than revealing it. At the very least, let's make a config variable for this so people can choose.

**Comment by Xymanek** [comment]
Exactly @ansabalirai. The idea of retals is something that should stimulate player holding some people in reserves, lest they be punished. When I was testing Alpha 4 I found myself constantly looking at that screen to "predict" my future usage of personnel and their availability.

I also thought about grading the ETA in words, but that will just incentivize the player to learn the correlation between the working and the timing by (again) constantly looking at that screen

**Comment by Xymanek** [comment]
@cannonfodder1 agreed on discord:

> I'm thinking we take it out, put it as a config option if possible, and bury that config option somewhere in the deep recesses of XComInfiltration.ini

**Comment by Xymanek** [comment]
I just had an idea: what if we show it only on end-of-month report? That way the player can have some sort of indication on the timing, but the meta playing of looking at the screen is still countered

**Comment by Xymanek** [comment]
I went with "always off", but I'm open to suggestions

**Comment by ansabalirai** [comment]
I think showing it once a month is a fair compromise

**Comment by Xymanek** [comment]
We could also change the text somehow... Maybe "more than a month"/"less than a month"?

**Comment by cannonfodder1** [comment]
I'm in favour of turning it off entirely. You can still sort of cheese it if you know that it's more than a month away.

**Comment by Xymanek** [comment]
Yeah, you are right. I was thinking more about it.... If we went the supply drop route, then we would be creating the same information issues that LW2 had that we wanted to not repeat
