### ISSUE TITLE
Basic utility items are too expensive

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#321]
Medikits, flashbangs and smokes are not at all balanced for the CI economy. We could make them infinite from the start or reduce their prices drastically.

**Comment by cannonfodder1** [comment]
Does this sound reasonable:
Smokes for 2$
Flashes for 3$
Medikits for 5$

Smokes are practically worthless and flashbangs have enough tradeoffs with frags to justify a low cost. Medikits are... medikits. You need a lot of them. Controversial bonus idea: frags for 4$?

**Comment by Xymanek** [comment]
Leave grenades infinite, as otherwise we would need to mess a lot with the 1st utility slot behaviour (to disable "must be equipped")
What's the vanilla values for comparison with other stuff?

**Comment by cannonfodder1** [comment]
Medikits and flashbangs are 35 supplies, smoke grenades are 25. Far too high if you have to build more than 2 per campaign like in CI.

**Comment by Xymanek** [comment]
Well... your prices seem basically free. Maybe 10-13-15?

**Comment by cannonfodder1** [comment]
Well, I'm kinda just doing the "multiply everything by 1/6" strategy (resulting in prices of 4-6-6) and then moving stuff to balance things out. Smokes are pretty worthless, flashbangs are hardly better than frags, and medkits aren't that good without the accompanying perks of a soldier class.

I think those prices are a little high. Now, it depends on what your mod setup is, but personally with beta strike enabled I usually like a 50/50 mix of frags and flashes. I suppose for that type of game we could recommend people use Infinite Starting Items.

**Comment by Xymanek** [comment]
I don't think that approach works here because it was made for converting infinite items to finite, but the ones in question here were always finite to begin with

**Comment by cannonfodder1** [comment]
That's a good point. Alright, 10-13-15 is good enough for a first pass.

**Comment by Xymanek** [comment]
Fixed by #328
