### ISSUE TITLE
Investigate DLC2 behaviour

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#325]
It's probably doing weird stuff with infiltrations

**Comment by Xymanek** [comment]
Notes to self:

* POI replacement (if non-integrated) breaks because we don't set `MissionState.POIToSpawn` before starting the mission
* POI replacement (if non-integrated) breaks because it checks missions calendar spawn dates
* The real big issue is `UpdateRulerSpawningData` in `UpdateMissionSpawningInfo` (in that function in general)

IMO the ruler should be rolled when infil reaches 100% and keep that till launch (while infil is going, the ruler will be ineligible for other missions). Chosen would be disabled in such case (but not visible to player)

For assaults, just use normal logic, but exclude rulers who are currently waiting on infils. For rulers waiting on infils, we could perhaps use the same state vars as for rulers waiting in facilities

**Comment by Xymanek** [comment]
@cannonfodder1 is there any reason why we are choosing the POI after mission instead of on mission spawn like the base game?

https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/328975c90548c2603c007e51cbbfeb3dcb9bce0f/CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc#L597-L608

This currently breaks DLC2/3's non-integrated mode where they replace `MissionState.POIToSpawn` inside `DLCInfo::OnPreMission`

**Comment by cannonfodder1** [comment]
@Xymanek It's been a while, but I'm fairly sure that I did it that way because that's how the vanilla classes do it. I don't have DLC2, so maybe that changes things around?

**Comment by Xymanek** [comment]
No, that's definitely not how it works in base game (sans any DLC). Check `X2StrategyElement_DefaultMissionSources` - `SpawnGuerillaOpsMissions`, `SpawnSupplyRaidMission` (and others)

**Comment by Xymanek** [comment]
Marking as resolved/closed as #396 and #396 fixed main issues.

"POI replacement (if non-integrated) breaks because it checks missions calendar spawn dates" remains unfixed, however, the worst that happens is that the timing is slightly off, but the POI itself will still spawn (since the calendar is still ticking, just with blank spots)
