### ISSUE TITLE
Create set spawning order for first month

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#330]
Right now, your first few chains are random. This can really screw over the player in some cases, so we should make sure they get an engineer as their first mission. Supply extraction and scientist chains should also be guaranteed to happen at some point before the end of the second month.

**Comment by Xymanek** [comment]
Tagging as Beta 2, as I suspect that after CA/POI overhaul this will change slightly

**Comment by Xymanek** [comment]
Is this implemented by #341?

**Comment by cannonfodder1** [comment]
Partially. The issue description above also suggests making sure that a scientist and a supply reward is given by the end of the second month, but I think that should happen anyway because what you have in the deck at the start of the game (4 chains I think) should be exhausted before the end of the second month.

**Comment by Xymanek** [comment]
Is this still relevant?

**Comment by cannonfodder1** [comment]
I don't think so, with #422 done and #370 on the horizon, there's little need for a set spawning order.
