### ISSUE TITLE
Prepare one-click-install workshop collection(s)

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#337]
One thing that LW2 did is that the entire thing could be acquired with one click and was guaranteed to work and be balanced. In CI planning, we opted to make things modular to give players more choice, but that doesn't mean that we should make it complicated for players who want a simple installation experience.

I propose the following modlists:

* Vanilla game with better strategy - only CI with dependencies
* LW2 classes - CI, dependencies, LW2 classes, some minor faction soldier tweaks, aba, slightly extended mission timers mod, MW
* LW2 classes hardcore - above + yellow alert + some CX enemies
* Proficiency classes - same as LW2 classes option, but with proficiency classes (+ faction soldier ones) + yellow alert (since the classes are designed with it mind)
* Proficiency classes hardcore - dystopian turn order, more CX enemies?

We could also make "Opinionated fixes/QOL" collection since some things like "surgical fix" is obsolete in CI

**Comment by Iridar** [comment]
That would certainly be useful. It would also be nice if somebody (guess it'll have to be me, eventually) were to maintain a collection of relevant QOL / fixes / compatible UI improvements mods. With strict screening for bad coding practices and bugs in general. So many mods on the workshop are inherently broken and spam redscreens..
