### ISSUE TITLE
Add Infiltration and Deterrence stats in the loadout UI for each item

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#340]
We should on OPTC loop through InfilModifiers and add `UIStatMarkup` lines for each item. Somewhat relatedly, we should find a word other than Infiltration Duration to describe the number of hours an item takes to infiltrate. Covertness doesn't work, because a higher stat corresponds to less stealthy. Bulkiness perhaps? Discuss.

**Comment by Xymanek** [comment]
So far we don't show exact deterrence values anywhere (on purpose). Might be a bit weird to show the exact one on the item
