### ISSUE TITLE
Review our utility items

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#344]
We've got `HoloProjector` and `AdaptiveCamo` utility items (created in `X2Item_InfiltrationUtilityItems`) but they were implemented so long I ago that I have no idea what they even do...

We should review their behaviour and cost/requirements in the current environment

**Comment by cannonfodder1** [comment]
My official recommendation after discord discussions is that we scrap these, they serve no real purpose and were a bad idea I came up with for no particular reason all the way back in Alpha.

**Comment by Xymanek** [comment]
I concur with that recommendation

> all the way back in Alpha

Probably even pre-Alpha
