### ISSUE TITLE
Create the rest of POIs/CAs

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#345]
Some of CAs didn't make it into Beta 1 (#335) but we still should implement them for next release

**Comment by cannonfodder1** [comment]
The only ones I approved that didn't make it in is Lone Survivor POI and Recover Lost Item CA, which if I'm being honest aren't the most impactful and I frankly don't think they are worth the development time at this critical moment

**Comment by Xymanek** [comment]
Ok, moving this to post-release (cuz I think that they are still good)

**Comment by Xymanek** [comment]
Not going to happen as this is not critical to CI and can be easily implemented in separate mod
