### ISSUE TITLE
Chosen can appear on an infil started before the first retaliation

### ISSUE THREAD

**Issue by ansabalirai** [WOTCStrategyOverhaul/CovertInfiltration#346]
If the mission is launched after the retal mission spawns

**Comment by Xymanek** [comment]
Note to self: activate the objective on mission exit/skip, but manually force the chosen onto mission site. Will probably require re-implementing the chosen logic for assault missions

**Comment by Xymanek** [comment]
Note to self: add CHL `OverrideAddChosenTacticalTagsToMission` event to `XComGameState_HeadquartersAlien::AddChosenTacticalTagsToMission`
