### ISSUE TITLE
Create static sitrep config for third-party faction sitreps

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#348]
Right now, third-party faction mods have no way to make their enemies appear in CI. Even the Lost are missing on infiltration missions. A config array should be added that specifies which sitreps contain these third parties, then logic created to add them to some missions as 100% chance to trigger sitreps that cannot be altered by overinfiltration.

**Comment by Xymanek** [comment]
MrCloista has been building sitrep bridges that incorporate enemy factions as risks. Considering that the risk removal was nerfed to 175%, I think this a good solution for introducing them to infils. Also note that "For assault missions, there is a 50/50 chance to not get any SitReps or get 1 risk and 1 tier 1 bonus" (our wiki).

Additionally, the `DLCInfo::PostSitRepCreation` hook is called when the mission becomes available for the player (100%) - other mods can force sitreps (that will unaffected by infil) via code. I do not see a need to do more things than this

> Even the Lost are missing on infiltration missions

They are present if the mission takes place on the abandoned plot type 

***

One thing that I may be inclined to do is to show the sitreps on squad select and call `DLCInfo::PostSitRepCreation` when the mission spawns - that way mission/plot force sitreps are visible on loadout and [Raider Faction Bases](https://steamcommunity.com/sharedfiles/filedetails/?id=1601260788) can do its job and be visible to player on loadout as well

**Comment by Xymanek** [comment]
Another thing to note: I considered making logic for an additional roll for non-infil-affected sitreps on mission spawn, but I think there is enough variety going on in CI that random per-mission stuff is unnecessary.

That said, I'm open to implementing it as a SWO

**Comment by Xymanek** [comment]
See #140 for more details and a couple of other hooks

**Comment by Xymanek** [comment]
Closed in favor of #361
