### ISSUE TITLE
Long delay before UI update when soldier removed from squad

### ISSUE THREAD

**Issue by ArcaneData1** [WOTCStrategyOverhaul/CovertInfiltration#35]
When a soldier is removed from the squad on the Squad Select screen, it takes a long time for OnSquadSelectUpdate to fire (varies around 10 seconds and over), meaning the UI is not updated with the new information immediately.

**Comment by Xymanek** [comment]
Fixed in robojumper/robojumperSquadSelect@9f6d1d38e219a18486be51a1f99497577f5cefd9
