### ISSUE TITLE
Assault missions not appearing in Covert Operations.

### ISSUE THREAD

**Issue by xmd1997** [WOTCStrategyOverhaul/CovertInfiltration#352]
When scanning the Geoscape the game notifies me when new assault mission opportunities pop up such as "Protect The Device" and "Gather Advent Supplies" but when I go to the Covert Ops mission UI, there isn't any new mission to select and deploy a squad. Note, that it seems that I can still be able to undertake missions in order to advance a chain, I'm currently on the rescue engineer chain right now. But so far within this campaign, I'm only deploying one full squad as of now.

- **Campaign Difficulty:** Rookie, then switched to commander on the second mission.

- **Mods in use**

1. A Better ADVENT: War of the ChosenBy: DerBKItem
2. ADVENT Warlock - WotCBy: Ashlynne_LeeItem
3. AugmentationsBy: MusashiItem
4. Better Second Wave Mod SupportBy: -bg-Item
5. Musashis RPG OverhaulBy: MusashiItem
6. Primary SecondariesBy: MusashiItem
7. Pyrrhic VictoriesBy: RealityMachinaItem
8. WotC Combat KnivesBy: MusashiItem
9. WotC Stealth OverhaulBy: MusashiItem
10. WotC Tactical SuppressorsBy: MusashiItem
11. WotC Vest SlotBy: MusashiItem
12. WotC: robojumper's Squad SelectBy: robojumperItem
13. [WotC] A Better Advent: Enemy ReskinnerBy: LagoItem
14. [WOTC] Adv Priest RevampedBy: MrShadowCXItem
15. [WOTC] Advent General RevampBy: MrShadowCXItem
16. [WOTC] Alien Elite PackBy: hectorzxItem
17. [WotC] Gene ModsBy: ∑3245Item
18. [WOTC] LW2 Secondary WeaponsBy: shiremctItem
19. [WotC] Mission Overhaul: CoreBy: ∑3245Item
20. [WotC] Mission Overhaul: MercuryBy: ∑3245Item
21. [WotC] Mod Config MenuBy: gubyItem
22. [WOTC] Open Squad Select at any timeBy: Astral DescendItem
23. [WOTC] Point-Based Not Created EqualBy: shiremctItem
24. [WOTC] Rocket LaunchersBy: IridarItem
25. [WOTC] Stats on New Promotion ScreenBy: Astral DescendItem
26. [WoTC] XCOM Psi Overhaul [NEW UPLOAD]By: KyuubicleItem
27. [WOTC] Yellow Alert GameplayBy: RedDobeItem
28. [WOTC] Yellow Alert SpawningBy: RedDobeItem
29. [WoTC]ADVENT SniperBy: FarkyrieItem

**Comment by ansabalirai** [comment]
If I understand correctly, you are looking for protect the device and similar sort of missions in covert operations? They are so called instant response missions and can be launched immediately (i.e. conventional squad outfit and fly on skyranger). You should see the mission icon the bottom right on the geoscape.

Also, the core theme of this mod is that you are able to deploy multiple squads, so you should do that :)

**Comment by xmd1997** [comment]
Oh, your right. I see. I apologize then. False alarm everyone.

**Comment by cannonfodder1** [comment]
No worries. "Assault" missions mean the old-style launch immediately type of stuff from vanilla. Covert Actions are always in the covert ops menu. Infiltrations are in the covert ops menu until they reach 100% infil, and then they go to the mission list. Assaults are in the mission list from the start.
