### ISSUE TITLE
Spawn the first chain earlier

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#359]
Currently, the very start of the campaign is very slow - you need to wait for the first chain to spawn and then wait for your guys to infiltrate it.

I think we should set starting work value to non-0, so that the "intensive" gameplay starts a bit faster

**Comment by cannonfodder1** [comment]
This was an oversight, it should have been set to above zero in Beta 1 (and I believe it was for an earlier Alpha)

**Comment by cannonfodder1** [comment]
Looks like it isn't set to 0, it's set to 50k and a spawn requires 100k, plus or minus 33k. I'm going to set it to 90k and disable the spread for the first chain.
