### ISSUE TITLE
Troop Transport Raid can roll timer sitreps even though the mission doesn't have a timer (afaik)

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#363]
![troop_transport_timer_sitrep](https://user-images.githubusercontent.com/44277211/68984252-5d3c8380-080f-11ea-8aed-a91f6bfaaced.png)

**Comment by Xymanek** [comment]
https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/f12cf8583fa75d0fc019e3e17884b9407e8a4c73/CovertInfiltration/Config/XComGameData.ini#L135-L136

`MissionType` needs to be replaced with `MissionFamily`

**Comment by Xymanek** [comment]
While we are it, we should also check if the same needs to be for other entries

**Comment by Xymanek** [comment]
Reassigning to myself as the issue lies with how negative sitreps/risks are selected for infils (currently they bypass the requirements check)
