### ISSUE TITLE
Error Message about missing rewards at the end of the mission

### ISSUE THREAD

**Issue by yoshimo** [WOTCStrategyOverhaul/CovertInfiltration#364]
Various missions like rescue a vip will result in errors about CI having troubles with the mission reward string.
https://pastebin.com/PiBRRyLp

**Comment by Xymanek** [comment]
"Add VIP Loot" doesn't exist neither in base game, nor in this mod... Which makes me think that it's from another mod. What mods do you have?

**Comment by yoshimo** [comment]
I am running with these:

`

Mod Achievement System
--
No Drop-down Lists
Insider Knowledge Fix
Defense Matrix Sabotage Fix
Custom Soldiers Evac Zone Fix
Spectre Vanish Fix
Skulljack Feedback Fix
Missing Packages Fix + Resource
Missing Packages Fix - Parcels and Maps Edition
Yet Another F1
[WotC] Peek From Concealment UI Fix
WOTC - Extended Information!
WOTC Show Enemies and Terrain on Mission Planning
Upgrade Reminder [XCOM2 Vanilla & WotC]
[WotC] Mod Config Menu
[WotC+Classic] TacticalUI KillCounter
[WOTC] Peek From Concealment
WotC Stealth Overhaul
WotC Tactical Suppressors
Hack Plus - WotC
[WOTC] New Promotion Screen by Default
WOTC Nice Mission Debriefing
[WOTC] Cost-Based Ability Colors
WotC: Show GTS Class Counts
[WotC] Gotcha Again
WOTC Show Tech Path
Lost Autofire
Simple True Concealment
Show More Buff Details
Upcoming Events [WotC]
Avenger Defense Bondmates Fix
[WOTC] Hours Instead of Days
[WOTC] Additional Icons
[WOTC] LifetimeStats
Maps by Vozati [WotC Edition]
WC_LAByrinth
Chosen Dark Events Fix
[WOTC] Tactical Options
[WotC] Revival Protocol Fixes
[WOTC] Ability Interaction Fixes
[WOTC] Faceoff Ammo Fix
[WOTC] Carry Unit Fix
Tower Detection Fix [WOTC]
Remove Missing Mods for WotC
Capnbubs Accessories - WotC
WotC: robojumper's Squad Select
[WoTC] Mercenary Plasma Hero Weapons
[WoTC] Mercenary Plasma Weapons
X2WOTCCommunityHighlander
[TLP] Legacy Operation Fixes
[WOTC] Stats on New Promotion Screen
[WOTC] Revert Overwatch Rules Change
[WOTC] Additional Soldier Console Commands
Better Second Wave Mod Support
Improved Camera Updated WotC
Blackmarket Usage
Make Heals Persist
CovertInfiltration
[WOTC] Open Squad Select at any time

`

**Comment by xilleto** [comment]
The mod Tactical Options allows VIPs to collect loot. Might wanna check there.

**Comment by yoshimo** [comment]
The option itself is turned off. I only allow gremlins to grab loot.

**Comment by Xymanek** [comment]
The bug is in Tactical Options mod, it's just noticeable when the next piece of code runs, which happens to be from this mod

**Comment by Xymanek** [comment]
Just to clarify: I'm talking about `Game State Created but Never Added to History` and the following text. The 
```
[0840.69] CI: No packages to read from!
[0840.69] CI: Something went wrong in reward string!
[0840.70] CI: No packages to grab from!
```
part is most likely a different problem, but the information provided here is not enough to diagnose it

**Comment by yoshimo** [comment]
What more than a logfile would you need to get to the bottom of it @Xymanek ?

**Comment by Xymanek** [comment]
A save file from when the rescue mission itself was **spawned**
