### ISSUE TITLE
Alien Corpses CA is missing all localization

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#365]
![alien_corpses_CA](https://user-images.githubusercontent.com/44277211/68995789-d41a6080-0891-11ea-8e08-b30e3159ca39.png)

**Comment by bstar1million** [comment]
There seem to be two different versions of the Corpses CA or there is a bug where sometimes the localization doesn't appear. For this instance, the localization shows up:

![alien_corpses_CA_2](https://user-images.githubusercontent.com/44277211/68995827-60c51e80-0892-11ea-90b6-370b3bafac91.png)

Going to attach a save file as well.

**Comment by bstar1million** [comment]
[save_CA_test_bstar_corpse_loc.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/3854392/save_CA_test_bstar_corpse_loc.zip)

**Comment by bstar1million** [comment]
Noticed the image is different. Is the first one perhaps supposed to be a PCS CA?

**Comment by Xymanek** [comment]
Notice that when switching CAs, the UI will retain the old image if a new one can't be found

**Comment by cannonfodder1** [comment]
Unable to reproduce
