### ISSUE TITLE
Supply extraction mission reads as "landed UFO" and uses vanilla mission type

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#367]
Or perhaps the mission type was ours after all? Watching Sliv's video, he's getting a ton of reinforcements. Perhaps the new mission type spawning is working fine, but the objectives display still says "neutralize all enemy targets". See attached save below, progress time and mission will show up.

**Comment by Slivicon** [comment]
This save is just before the beginning of the video, and can be seen at this timestamp https://youtu.be/sNqlFkoimUk?t=319 - clicked scan on eastern US and in less then a day it spawned the landed ufo supply raid which wasn't a ufo: 
[save_Save 56_before_landed_ufo_supply_raid.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/3856050/save_Save.56_before_landed_ufo_supply_raid.zip)

**Comment by Xymanek** [comment]
Just watched the video, it seems like the only major issue is the objective text - "neutralize all enemies" should no longer show up and "evac all xcom" should be there from the start

+ the geoscape UI

**Comment by Xymanek** [comment]
Another issue I noticed is that the mission end screen says "supply raid" and doesn't display how many crates you got
