### ISSUE TITLE
Start campaign with a scientist and an engineer

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#370]
Chains approach to acquiring avenger staff is nice for planning aspect, but really slows down the start of the campaign (2 infils required). I propose that we just make the campaign with one of each and get rid of the "forced first chain is engineer" hack, since it still solves very little

**Comment by cannonfodder1** [comment]
In the spirit of the "everything comes from somewhere" theme we've got going, should Gatecrasher be made into a double rescue mission? Probably not because it would be a lot of work, but it would also be really thematic to start of the resistance with something meaningful instead of blowing up an inconsequential monument.

**Comment by Xymanek** [comment]
There is no "rescue multiple staff" mission type in vanilla. We would need to make a custom one

> something meaningful instead of blowing up an inconsequential monument.

It's called sending a message - "The Resistance is here!"

**Comment by Xymanek** [comment]
That said, I would prefer to change the thematic of starting mission to keep in line with "first retal is first time advent high administration hears about xcom". A "daring rescue" is a good candidate

**Comment by cannonfodder1** [comment]
There's also the gameplay feature of Gatecrasher being the mission that tells you if you're on the correct difficulty. Any changes to it need to be carefully balanced.

**Comment by Xymanek** [comment]
Also that. And we need to decide how much we want to stray away from "don't touch missions" (even though we did slightly already) but I think it could be justifiable in this case since no other mod changes gatecrasher (except LW, but they just removed the need to walk up to thing and clique the buuton)

**Comment by cannonfodder1** [comment]
As discussed in the discord, a replacement of Gatecrasher is going to be the solution for this issue.

**Comment by Xymanek** [comment]
Closed in favour of #378
