### ISSUE TITLE
Advanced Grenades don't upgrade grenades while equipped on Infiltration Mission

### ISSUE THREAD

**Issue by xilleto** [WOTCStrategyOverhaul/CovertInfiltration#371]
Finishing Advanced Grenades research while you have a soldier deployed equipped with Gas/Acid/Incendiary will not upgrade the equipped grenade to a bomb after the mission.

**Comment by Xymanek** [comment]
For reference: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/230, https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/289

**Comment by Xymanek** [comment]
Note to self: `class'X2StrategyElement_XpackStaffSlots'.static.CheckToUpgradeItems(NewGameState, NewUnitState);` on squad on post (infil) mission
