### ISSUE TITLE
Add option to suppress skulljack nag when it's deployed on another infil

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#372]
Probably should be an MCM option, on by default. Also completely disable for normal CAs

**Comment by ansabalirai** [comment]
Why not suppress it completely, i.e. regardless of whether it is deployed or another infiltration or whether I have one lying around in the inventory? I personally don't want to skulljack an officer until I really need to and I imagine most players playing this mod don't really need to constant reminder anyway

**Comment by Xymanek** [comment]
It's not the place of CI to change such place - I'm pretty sure there are other mods that make such changes. It does, however, make sense to prevent useless nagging which didn't account for how mission in CI work
