### ISSUE TITLE
Infiltration was ambushed, possibly because of Spider & Fly Dark Event

### ISSUE THREAD

**Issue by ciasputnikmonroe** [WOTCStrategyOverhaul/CovertInfiltration#373]
I have 5 guys infiltrating on a rescue a VIP mission. Suddenly it popped up that they were ambushed. The mission began and only three of them were on the map. I managed to get them to the extraction but two of them were gravely wounded. After the ambush was complete they are still on the map infiltrating. I can select the two that were wounded in the barracks, even though it says they are infiltrating and one of them only has 3

[SaveData.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/3886361/SaveData.zip)

 health (likely because he's gravely wounded from the ambush). If I select them on the  strategic map my only options are view squad, wait, and begin assault. Is this normal behavior?

I went to the barracks to check on them to double check how many days they'd be out wounded, but it said they are infiltrating instead of wounded.
Unlike other infiltrating soldiers, I can select them in the barracks and view them.

Attached ZIP includes two save files. "save_AUTOSAVE- Campaign 17, Mission 11, Turn 9" which is near the end of the ambush escape mission and "save_Save 9_1" which is a strategy layer save from a little earlier, Spider and Fly dark event is active, if you check out infiltration missions in the covert ops ring they all list ambush as a risk.

**Comment by Xymanek** [comment]
Found the problem - DE risks are disallowed from showing up on existing CAs but will still apply to CAs that are spawned after the DE is activated

**Comment by Xymanek** [comment]
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/692
