### ISSUE TITLE
Evaluate using "global effects" to say "chain is advanced"

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#379]
![image](https://user-images.githubusercontent.com/2865341/69703803-e77fc400-10fa-11ea-9b98-72d32eb4199a.png)

Could be an interesting place to put it

**Comment by cannonfodder1** [comment]
Why put it there? This is after the player has made a radio relay and done an activity in an adv. chain

**Comment by Xymanek** [comment]
> This is after the player has made a radio relay and done an activity in an adv. chain

I'm confused as to what you mean

**Comment by cannonfodder1** [comment]
> I'm confused as to what you mean
Why does the player need to know that the chain is advanced when they complete a mission in an advanced chain? The time when we want them to know that it's advanced is before they've built a radio relay, to encourage them to build one and unlock the advanced chains.

**Comment by Xymanek** [comment]
Oh i see the confusion. By "advanced" I meant to say that the mission moved the chain from stage 2 to stage 3 (or similar)

**Comment by cannonfodder1** [comment]
Ohhhhhhhh. Yup that was confusion of the highest order. I approve of this plan

**Comment by Xymanek** [comment]
Ok, since this is out of the way, there are a few other things to consider:

* Some missions already list "advance chain" is the rewards (on the left in that screen)
* What to do about non-mission stages? e.g. CAs

**Comment by cannonfodder1** [comment]
Those two points cancel each other out, the only activities that use "Advance Chain" are the CAs which come with their own debriefing screen where the reward is highlighted.

**Comment by Xymanek** [comment]
Ok, that kinda helps 😄 Should it be the following way:
```
GLOBAL EFFECTS:
Chain advanced
```
Or something different?

**Comment by cannonfodder1** [comment]
I think we should just reuse the `Reward_Progress` string, which upon reflection should be changed from `Advance Chain` to `Chain Progress`
