### ISSUE TITLE
Supply extraction mission can be too easy

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#383]
We should exclude that mission from rolling the Comms Jamming sitrep, which makes it far too easy to setup overwatch traps for the reinforcement pods.

**Comment by cannonfodder1** [comment]
Advent Air Patrols also affects reinforcements, and should probably also be disabled for this mission.

**Comment by Xymanek** [comment]
Comms Jamming will work only on first RNF though. Air patrols I agree - it will be counter-intuitive
