### ISSUE TITLE
Comms Jamming SITREP is bugged

### ISSUE THREAD

**Issue by ChrisTheThinMint** [WOTCStrategyOverhaul/CovertInfiltration#384]
It seems to be applying to all reinforcements but the first. Maybe the logic is the wrong way around?

**Comment by Xymanek** [comment]
Looking at the code, it doesn't seem like there is any checks for the "how many times it triggered" at all

**Comment by statusNone** [comment]
pretty sure when i wrote this the idea (at least as far as i was aware) was to apply it to all RNFs for that particular mission.. if we want it to only trigger for the first pod i think i'll need a XCGS variable to save a boolean value for once it's been triggered.. is that what we want to do?

**Comment by Xymanek** [comment]
Yep, we want it to trigger only once.

There is already a state var for air patrols sitrep on XCGS_CIInfo, you can add another one right next to it.
