### ISSUE TITLE
Improve Phalanx/Congregation sitreps implementation

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#386]
The description states:

> All enemy pods include a Shieldbearer

However, the behaviour is more like

> All enemy pods which do not have an explicit composition or a leader override set, replace the leader with a Shieldbearer and limit the followers accordingly

This is 

1) not what the description states
2) a much bigger change to enemy setup than intended

We should make use of the **DLCInfo:PostEncounterCreation** hook to actually replace one of the followers with a shieldbearer. We also need to decide (and clarify in the description) what to do when

* the pod consists of 1 unit - IMO do nothing
* the pod has a preset composition (i.e. no "open"/random slots) - IMO add another unit to it

Same goes for Congregation (same thing but priests)

cc @ChrisTheThinMint

**Comment by ChrisTheThinMint** [comment]
1 unit pods are decidely rare, so I agree with not adding any unit to them.

Preset pods are kinda tough. You gotta watch out that you don't accidentally add a unit to a chosen's pod or something like that. Adding units for free might also lead to an unexpected increase in strength in some cases.

**Comment by Xymanek** [comment]
About Chosen pods:

* The chosen itself is a 1-unit pod, so it's covered by first condition
* The stuff that they spawn (general, beastmaster, etc) are not forced composition, instead they use a special spawn distribution list (i.e. "candidate list"). But this also brings up a good question - what to do with pods such as these?

One potential solution would be to just exclude all reinforcements altogether
