### ISSUE TITLE
Possibility to choose a SPARK while it is in infiltration.

### ISSUE THREAD

**Issue by nicodede62** [WOTCStrategyOverhaul/CovertInfiltration#390]
Hi, I found a bug I think.

For an assault mission versus a chosen, I have the choice to put a spark who is already on a mission.
It's just for this mission, for an another infiltrating mission, I can't take it.

![Sans titre](https://user-images.githubusercontent.com/58703396/70460926-b8ccfa80-1ab7-11ea-8e40-7a5311c8192f.png)

**Comment by Xymanek** [comment]
Looks like it's this issue: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/665

**Comment by Xymanek** [comment]
Fixed in https://github.com/WOTCStrategyOverhaul/X2WOTCCommunityHighlander/commit/41299b02dc08fa85d17c5b58e21db71dc2d2aa73
