### ISSUE TITLE
Supply Drop messes with CA events

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#4]
If a CA event is running when the monthly Supply Drop happens, it's text will be overwritten with "Supply Drop", and the Supply Drop event's text overwritten with the CA's text, until the player clicks on the Covert Actions button or exits the Geoscape.

![20181017193459_1](https://user-images.githubusercontent.com/1369684/47127927-09462080-d244-11e8-8806-6991dd501150.jpg)

**Comment by Xymanek** [comment]
Didn't you fix this in 5c726215f1de52da33af7945682dc2fdbeea3644?

**Comment by cannonfodder1** [comment]
No, I fixed the "Select Covert Operation" ticker being placed at the top of the list instead of the bottom. I have no clue what's causing this issue, I'll look into it tomorrow
