### ISSUE TITLE
Make everything related to squad size configurable

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#406]
Lots of stuff needs to be given config variables and adjusted to work with that
- Maximum number of soldiers in a squad
- Amount of optional slots on an infil
- Number of infil size GTS upgrades (could hardcode this, not as important)

**Comment by Xymanek** [comment]
> Number of infil size GTS upgrades 

Loc would be an issue here. An easier solution would be to config how many slots each upgrade upgrades
