### ISSUE TITLE
Crew Limit config variables are only checked on new campaign

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#431]
We should find a way to make mid-campaign edits take effect, or in the worst case make a console command to reload the limit from the config.

**Comment by Xymanek** [comment]
I see no reason to rework the system - a lot of config/template changes in xcom2 won't make a difference when done mid-campaign - but a console command to recalculate the max makes sense

**Comment by Xymanek** [comment]
#455 adds a command to manually set the crew limit

**Comment by cannonfodder1** [comment]
> #455 adds a command to manually set the crew limit
This issue is resolved as per above
