### ISSUE TITLE
Infiltrations are counted as CAs on the monthly report screen

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#432]
Beyond the UX issues with this, it also seems to be affecting LSC.

**Comment by Xymanek** [comment]
This was already fixed in https://github.com/WOTCStrategyOverhaul/CovertInfiltration/commit/76e0b1a5b12f763484e51cd82fde7d0ff9699e6e

**Comment by cannonfodder1** [comment]
Reports inconclusive, requires testing to confirm

**Comment by Xymanek** [comment]
So i tested it and turns out they aren't record at all 😄 #446

**Comment by ansabalirai** [comment]
So, just for my clarification, this issue was closed because it was supposedly fixed in the commit for #446 , or just closed because it was not worth the effort?

**Comment by Xymanek** [comment]
There were 2 parts:

* Being recorded as CAs - fixed in 76e0b1a
* Not being recorded as missions - fixed in 79107c692a896dbe7d1f454d558b9e4fed7ff908
