### ISSUE TITLE
Tactical Analysis bonus from overinfiltration applies to friendly resistance soldiers

### ISSUE THREAD

**Issue by tmichaelzhao** [WOTCStrategyOverhaul/CovertInfiltration#433]
I infiltrated a mission to the 250% threshold and received the Tactical Analysis bonus, which deprives enemies of one action after being activated during XCOM's turn. In the mission, a pod of friendly resistance soldiers activated/scattered immediately after XCOM's drop-in, and was affected by the Tactical Analysis debuff on the first Resistance Action turn.

**Comment by Xymanek** [comment]
What mission type was that?

**Comment by tmichaelzhao** [comment]
I'm not certain, but I believe it was "Rescue resistance faction affiliated scientist/engineer", where I started with an extra controllable faction hero unit, along with the friendly NPC resistance soldiers.

**Comment by Xymanek** [comment]
Was it "Emergency Extraction" from https://steamcommunity.com/sharedfiles/filedetails/?id=1133287457?

**Comment by tmichaelzhao** [comment]
Yep, that sounds exactly like it.

**Comment by Xymanek** [comment]
Fixed in 3d20b6d1a6769ecfe682238ee97872fcb501f389
