### ISSUE TITLE
Full localization pass for B3

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#442]
Currently, the most prominent issue is in the MCM option text and tooltips, but I'm sure there are others that will need cleanup before Beta 3 is released.

**Comment by bstar1million** [comment]
![proving_ground](https://user-images.githubusercontent.com/44277211/75085333-692f9400-5528-11ea-9a01-341cb23f5405.jpg)

Change 
`Summary="The Resistance Ring allows managing Resistance Factions and assigning them orders on monthly basis"`
to
`Summary="The Resistance Ring allows managing Resistance Factions and assigning them orders on a monthly basis."` ("a" and period missing).

**Comment by Xymanek** [comment]
You will need to improve the loc I made in #455 and (possibly) pick a new image - I dislike the current one cuz it shows "holes" in avenger

**Comment by Xymanek** [comment]
One thing to consider is whether we will consider the loc final or not (after this issue is handled).

This will "control" whether we allow people to submit translations, or we delay that until workshop release

**Comment by Xymanek** [comment]
Need to rewrite the tutorial since #490 introduced more space for the text

**Comment by Xymanek** [comment]
We should also probably add a tutorial when you first go into build items after researching t2 weapons/armor that explains how the individual build stuff is meant to be used

**Comment by Xymanek** [comment]
TODO:

https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/10b4be92ba5a97d753e52eb22b81bcdc1c6d9a86/CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc#L894

https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/10b4be92ba5a97d753e52eb22b81bcdc1c6d9a86/CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc#L867

**Comment by cannonfodder1** [comment]
Closed in https://github.com/WOTCStrategyOverhaul/CovertInfiltration/commit/7faafdd443df347472c12377525e58830f0fbf44
