### ISSUE TITLE
[EPIC] Final activities review

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#445]
Beta 3 will be the last version where we are to make design changes, so we should do one last pass on activities that the player does.

Includes:

* #322
* #378
* #439

**Comment by cannonfodder1** [comment]
Feedback is that the structured nature of activity chains makes the game too repetitive. To solve this, I think we should create several 'variants' for each chain that have different activities, but similar rewards.

**Comment by cannonfodder1** [comment]
After some thought, I think a good approach would be to turn the `Stages` array of names in the X2ActivityChainTemplate into an array of structs, which hold the Tag and Type of the activity desired. X2ActivityTemplates, meanwhile, get Tag and Type variables. This would mean only a few changes need to be made to existing code, however I may need to move localization from an activity basis to a chain basis, with preset narratives for each stage. See the spreadsheet linked below for more info on Tags and Types.

https://docs.google.com/spreadsheets/d/1TsgV3QWHPvyL9R_wI5ZzYDbyTEgtQiA3dZ1yNlChgsY/edit?usp=sharing

**Comment by Xymanek** [comment]
The spreadsheet makes it sound like the switching is done inside the activity <> mission type mapping, not the chain <> stages mapping as your comment implies?

**Comment by cannonfodder1** [comment]
The spreadsheet had an earlier guess of how I would make it work, but after looking at the code I think it's better to map it on the chain side instead of the activity side. Updated the spreadsheet info page.
