### ISSUE TITLE
The Hive compatibility: Exclude timer sitreps from Hive Terror missions

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#453]
Right now sitreps like Well Rehearsed can spawn for The Hive terror missions. Add these missions to exclusion list in  XComGameData.ini under [CovertInfiltration.X2EventListener_Infiltration]

**Comment by bstar1million** [comment]
MissionFamily="HIVETerror"

**Comment by Xymanek** [comment]
Messaged MrShadowCX on discord to add required config to "The Hive More"

**Comment by Xymanek** [comment]
Solved on the hive's side

**Comment by bstar1million** [comment]
Not actually solved it seems. 

I just got another Hive Terror mission that instantly ended after my first turn was done, with zero enemies on the map.

- Force Level: 5
- Mission: MissionName="HIVESupplyExtractionTerror", sType="HIVESupplyExtractionTerror"
- Tried deleting & redownloading the mod, didn't do anything.
- Tried deleting & refreshing config, didn't do anything.

Save is attached:
[save_hive more terror_1.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/4247608/save_hive.more.terror_1.zip)
