### ISSUE TITLE
Rookie POI giving too many rookies

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#454]
Considering how much rookies cost in CI and how much more valuable they are as a resource, I suggest reducing the maximum number of rookies from POIs to 3.

To ensure that the POI is not stronger on Legend in relation to others, I also suggest slightly reducing the cost of rookies on Legend, perhaps to 60 - 80 feels excessive. Another solution would be to change the POI duration on Legend to account for the higher relative value of the reward.

Configuration file: 
XComGameBoard.ini
[POI_Rookies X2PointOfInterestTemplate]

**Comment by Xymanek** [comment]
Currently being discussed on discord

**Comment by cannonfodder1** [comment]
Rookie recruitment cost is also getting heavily reduced as per discussions on discord
