### ISSUE TITLE
Bug: RequiredTechs for Beam Shotgun/Cannon are swapped

### ISSUE THREAD

**Issue by bstar1million** [WOTCStrategyOverhaul/CovertInfiltration#456]
I think the RequiredTechs for the BM Shotgun and Cannon were swapped.

It should be HeavyPlasma for the cannon and AlloyCannon for the shotgun. Naming seems to be misleading.

**Comment by cannonfodder1** [comment]
Fixed this already in commit 11f11ed

**Comment by Xymanek** [comment]
Well, at least now we got a record of the fix in the milestone 😄
