### ISSUE TITLE
LW2 Secondaries bridge has unbalanced item prices

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#461]
I suggest lowering them by a third or so, and keeping the current prices as Legend.

**Comment by bstar1million** [comment]
Pull request: https://github.com/WOTCStrategyOverhaul/CIBridge_LW2Secondary/pull/1

**Comment by cannonfodder1** [comment]
This PR is now defunct as the entire bridge is no longer needed. Shiremct is integrating it directly into LW2 Secondaries.
