### ISSUE TITLE
Update all bridges to the new modifier system

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#467]
See #462 for details

**Comment by Xymanek** [comment]
Also waiting on implementation of #336 and #381

**Comment by cannonfodder1** [comment]
Also need to rewrite the technical compat wiki page

**Comment by bstar1million** [comment]
**SMG PR:**
https://github.com/WOTCStrategyOverhaul/CIBridge_SMG/pull/1
**LW2 Secondary PR**
https://github.com/WOTCStrategyOverhaul/CIBridge_LW2Secondary/pull/2

**Vektor Crossbows commit:** 
https://github.com/WOTCStrategyOverhaul/CIBridge_VektorCrossbows/commit/23e2450e6ed23a7953e4af031e4a543cdfe7bcb4
**Beowulf Rifles commit:** 
https://github.com/WOTCStrategyOverhaul/CIBridge_BeowulfRiflePack/commit/363a2cf57ca26f21cc9873d193e8fa7dbe62e631
**Pathfinders commit:** 
https://github.com/WOTCStrategyOverhaul/CIBridge_Pathfinders/commit/1fcbcf223a0b649ce36e49a888686d890abd10a3
**Rocket Launchers commit:** https://github.com/WOTCStrategyOverhaul/CIBridge_RocketLaunchers/commit/100ebfaa56a9af5deae694b2d41e0fc9f79fbe30
**Mercenary Plasma Weapons commit:** 
https://github.com/WOTCStrategyOverhaul/CIBridge_MercenaryPlasmaWeapons/commit/c9416c0b7a0bfa10671c5caf88363ab656ced923
