### ISSUE TITLE
Fix detection radius modifier for disguises

### ISSUE THREAD

**Issue by ArcaneData1** [WOTCStrategyOverhaul/CovertInfiltration#47]
The disguises are supposed to reduce detection radius for the wearer, and the code is in place to do so, however it currently has no effect in the actual mission.

**Comment by Xymanek** [comment]
Are you sure there is no effect? [This](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/pull/10#discussion_r231647071) and [this](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/pull/10#discussion_r232400385) tells me that the problem is with the UI, not actual gameplay changes

**Comment by ArcaneData1** [comment]
> 
> 
> Are you sure there is no effect? [This](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/pull/10#discussion_r231647071) and [this](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/pull/10#discussion_r232400385) tells me that the problem is with the UI, not actual gameplay changes

During the actual mission, whether the selected soldier is wearing a disguise or not, the enemy units' detection radii remain unchanged. Aren't your linked discussions just about displaying the radius reduction in the UI?

**Comment by Xymanek** [comment]
Ok, then it's confirmed that gameplay is affected.

Does the mobility buff apply? Also, what does [Yet Another F1](https://steamcommunity.com/sharedfiles/filedetails/?id=934236622) show with [Show More Buff Details](https://steamcommunity.com/sharedfiles/filedetails/?id=709499969) installed?
