### ISSUE TITLE
Clear warning on UISS if no mission can result from this CA

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#479]
Both Barn Cat and Mister Gruffle made the "mistake" of sending combat gear (like flashbangs) on CAs that do not result in missions (eg. no ambush risk). This is especially easy to do when just starting, when items are most "expensive" since you don't have a stockpile of resources

**Comment by cannonfodder1** [comment]
Best to put this in the newly expanded tutorial box for Covert Actions.

**Comment by Xymanek** [comment]
I was thinking more along the lines of a notice each time you do the loadout

**Comment by cannonfodder1** [comment]
> I was thinking more along the lines of a notice each time you do the loadout
The most quality way to do this would be to have a confirmation dialog, like "You have unnecessary items equipped, this mission will not result in combat, Are you sure you want to launch the mission? Yes/No" if the player has non-infinite non-deterring items equipped. I'm going to give it a shot and modify SSAAT to make it happen.

**Comment by Xymanek** [comment]
A popup might be a bit too intrusive... How about using the space where the mission plot type is displayed for missions to instead show "[triangle] Warning: You have unnecessary items equipped, this mission will not result in combat"

**Comment by cannonfodder1** [comment]
> A popup might be a bit too intrusive... How about using the space where the mission plot type is displayed for missions to instead show "[triangle] Warning: You have unnecessary items equipped, this mission will not result in combat"

Do you mind if I did a confirm popup anyway? I nearly finished making it last week.

**Comment by Xymanek** [comment]
One issue with the popup is that it's... late. E.g. player spends time thinking and gets feedback only when pressing the button, whereas a fixed text on screen is instant.

Also, isn't the biggest part detecting the extraneous items here, not the UI?

**Comment by cannonfodder1** [comment]
> Also, isn't the biggest part detecting the extraneous items here, not the UI?

Not really, but that's fine. I'll see if I can get some screen text happening
