### ISSUE TITLE
Recruit faction hero chain rewards a regular soldier

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#494]
Reported by Arubiano in discord

**Comment by Xymanek** [comment]
https://discordapp.com/channels/578606792448409610/639765230569783320/697145983523356723

**Comment by cannonfodder1** [comment]
This will need to be tested with the new Random Activity System since we aren't going to care about the behaviour of the old activity system going forward

**Comment by Xymanek** [comment]
#471 was merged already, what about this?

**Comment by cannonfodder1** [comment]
I was going to get to it later, by the time this came up I had moved on from #471 to another issue.
