### ISSUE TITLE
CA button remains visible when Avenger is in flight

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#5]
When the Avenger is in flight or when Avatar Progress happens, or any other instance in which most of the Geoscape UI disappears, the CA button remains in it's spot at the bottom of the screen. Should find out how the rest of the UI is hidden during these events and apply that to the button.

![20181017193243_2](https://user-images.githubusercontent.com/1369684/47127907-f5022380-d243-11e8-9a1c-1b69f141a1cc.jpg)

![20181017193356_1](https://user-images.githubusercontent.com/1369684/47127908-f5022380-d243-11e8-8962-fad7e4685770.jpg)

**Comment by Xymanek** [comment]
Interesting. The following code (used by the mission screen) properly hides all map ui:

```
GetHQPres().StrategyMap2D.Hide();
```

I guess there is some sort of internal "semi-hiding" mechanism used during flying (which leaves the time and resources panel visible)

**Comment by Xymanek** [comment]
Here is the code which hides ui mid-flight:

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/8954b83b97d6296e26003dea22ea32da2af76c4f/X2WOTCCommunityHighlander/Src/XComGame/Classes/UIStrategyMap.uc#L235-L268

**Comment by Xymanek** [comment]
Looking at that code, I have a feeling we will need a CHL event there
