### ISSUE TITLE
Run out of scan sites

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#500]
https://youtu.be/g_uKFBpPrNw?t=1945

The plan we to always have ~3 choices to scan

**Comment by cannonfodder1** [comment]
We could probably solve this by bumping up the Resistance Rumor reward from 1 POI spawn to 2 or 3 POI spawns.

**Comment by cannonfodder1** [comment]
Could alternatively be solved by ripping off or requiring the Multiple POIs mod

**Comment by Xymanek** [comment]
From description of said mod:

> NO MORE POIs POP UP AFTER A WHILE
Use the Rewards Deck Refresher mod, it's in the Requirements. It may not fix the issue however it's not 100% tested but it wont hurt. Suggest keeping # of POIs that spawn at 4 maximum for a long campaign.

Sounds like there is an issue with the game running out of POIs to pick for spawning. We should investigate it
