### ISSUE TITLE
Quest items bug/redscreen

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#505]
See https://github.com/WOTCStrategyOverhaul/CovertInfiltration/pull/471#discussion_r407934214

**Comment by Xymanek** [comment]
A bit of investigation: 

The quest items are filtered based on:

* Mission source (which is always `xyz` in our case)
* Mission type
* Reward type
* DE attached to mission site yes/no?

```
CI: ===============================
CI: Missions with quest items:
CI:   Recover
CI:   Recover_ADV
CI:   Recover_Train
CI:   Recover_Vehicle
CI:   Hack
CI:   Hack_ADV
CI:   Hack_Train
CI:   ProtectDevice
CI:   GP_Blacksite
CI:   GP_Forge
CI:   ChallengeHackWaterfrontRadio
CI:   ChallengeRecoverMissiles
CI:   ChallengeRecoverRotor
CI:   ChallengeRecoverChair
CI:   ChallengeRecoverManual
CI: ===============================
```

Excluding the GP and challenge missions, I would need a list of the infil/assault uses of these mission types with the applied reward types @cannonfodder1

**Comment by cannonfodder1** [comment]
`Activity_IntelligenceInfiltrate` = Hack and Recover
`Activity_IntelligenceAssault` = ProtectDevice
Both of those have two rewards, `Reward_Rumor` first and `Reward_SmallIntel` second

I don't think that Infiltrations are affected by this bug, I've only ever gotten the redscreen with Assaults, which means we're already covered with the existing config entry in XComMissionSources:

```
[XComGame.XComTacticalMissionManager]
+arrSourceRewardMissionTypes=(MissionSource="MissionSource_ActivityCI", RewardType="Reward_Rumor", MissionFamily="ProtectDevice")
```

**Comment by Xymanek** [comment]
I want to actually fix the problem instead of bandaiding it (now in 2 places) - that's why I asked for all of them. Anyway, thanks, will take a look later
