### ISSUE TITLE
Mission has invalid quest item and missing data on summary screen

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#509]
- Assault mission
- Item recovery
- Evacuated with objective
- Notable mods: Pyrrhic Victories, Mission Overhaul
- Version: beta 2.5

Save before mission launch: https://cdn.discordapp.com/attachments/639765305345835009/701499868421554226/save_Save_3_-_before_mission_-_item_fail

Save in-mission before evac: https://cdn.discordapp.com/attachments/639765305345835009/701499838117970010/save_AUTOSAVE-_Recover_item_fail

Refs:

* https://discordapp.com/channels/578606792448409610/639765230569783320/701482498022047787
* https://discordapp.com/channels/578606792448409610/639765305345835009/701499722090938469

**Comment by Xymanek** [comment]
Possible source of issue: XCGS_A_Assault can expire/remove the mission while avenger/skyranger is en route: https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/e083a88cb2ba6715ed49be60d166dd8a26a97eb3/CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_Activity_Assault.uc#L39-L64
