### ISSUE TITLE
"Gather Intel" mission providing full reward but spawning "Save Intercepted Intel" anyway

### ISSUE THREAD

**Issue by RevZero** [WOTCStrategyOverhaul/CovertInfiltration#520]
I just had a "Gather Intel" mission. It said in the description, that "...rewards from this chain have a chance to be halved and made recoverable in a rescue...". I got the full 100 Intel (was listed as reward and my Intel went from 13 to 113), but a "Save Intercepted Intel" mission just popped up anyway.

Furthermore, the "Save Intercepted Intel" mission lists "1 Elerium Crystals" as reward!? I would have expected 50 Intel?

![20200515234730_1](https://user-images.githubusercontent.com/936992/82099193-0274dd80-9707-11ea-8f6d-490102c8e920.jpg)
![20200515234745_1](https://user-images.githubusercontent.com/936992/82099202-099beb80-9707-11ea-8e2e-10d7a4e22830.jpg)
![20200515234756_1](https://user-images.githubusercontent.com/936992/82099208-0e609f80-9707-11ea-9e6b-e00801beaf46.jpg)

[save_Save Intercepted Intel.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/4637264/save_Save.Intercepted.Intel.zip)

**Comment by cannonfodder1** [comment]
Possibly related to #410, it doesn't look like its fix (#460) made it into Beta 2.5.

**Comment by Xymanek** [comment]
Intel interception definitely works in beta 3 ("proved" in MG's first video), but we should add a check to `X2StrategyElement_DefaultComplications::SpawnRescueMission` to forgo spawning the mission in case nothing was intercepted
