### ISSUE TITLE
Sensor Fences breaks Gatecrasher by unlocking the prisoners too early

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#546]
Only occurs with one specific parcel, perhaps remove that parcel from the pool?

**Comment by Xymanek** [comment]
* How big is the pool?
* Would it be possible to get Sensor Fences author to to fix it form their side?

**Comment by cannonfodder1** [comment]
As far as I've seen, it's either three completely encased cells side by side in which case there's no problems, or one jumbo cell with cell bars instead of solid walls, which is the type that's causing the problem. The issue here is I have no idea where the pool for these mini-parcels is, I thought a parcel was the smallest segment of map that X2 had but these pieces are changing inside a single parcel.
