### ISSUE TITLE
Mission exit sequence indication that something was intercepted

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#550]
Properly a queued alert. Pick one of the small red/yellow ones with the something like this

> REWARD INTERCEPTION

> Commander, part of the resistance team transporting our recent spoils of war was intercepted! If we launch a recovery mission right now, we will be able to save the following

> [comma separated list of items (recovery mission reward)]

cc @cannonfodder1 review the text above and I will probably need a 2x1 image for the alert

**Comment by cannonfodder1** [comment]
> REWARD INTERCEPTION
> Commander, part of the resistance team transporting the spoils of war back to base was intercepted! About half of the resources never made it, and the situation for the resistance team on the ground is looking grim. If we launch a recovery mission soon, we should be able to save the rest of our loot.
> Rewards Intercepted: [comma separated list of items]
