### ISSUE TITLE
Exhaustive Training CA broken (sometimes doesn't have a promotion slot reward)

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#552]
As seen in MG's second beta 3 episode: https://youtu.be/VZog_QWFvJI?t=5973

**Comment by cannonfodder1** [comment]
Really not sure what to make of this bug, because as you can see in this screenshot I've done some exhaustive training but all of these have a promotion slot reward: 
![20201010180951_1](https://user-images.githubusercontent.com/1369684/95668086-0f65f380-0b24-11eb-8e26-8ebc3a692061.jpg)

**Comment by Xymanek** [comment]
Could he had a mod that removes CA soldier rewards? I recall seeing at least one such mod on workshop

**Comment by cannonfodder1** [comment]
> Could he had a mod that removes CA soldier rewards? I recall seeing at least one such mod on workshop

MG's modlist has Solder Development (https://steamcommunity.com/sharedfiles/filedetails/?id=1337050242) which removes CA stat boosts. It doesn't mention removing random promotions, but perhaps those are also disabled. I'll do some testing with that mod installed.

**Comment by Xymanek** [comment]
> which removes CA stat boosts. It doesn't mention removing random promotions

Internally both are implemented the same way - slot/unit reward

**Comment by cannonfodder1** [comment]
Maybe we can detect that there's no slot reward and disable the CA before it spawns? Or detect the mod itself and remove the CA from the spawning pool
