### ISSUE TITLE
Show Assault Mission expiration time when hovering over the mission icon

### ISSUE THREAD

**Issue by RevZero** [WOTCStrategyOverhaul/CovertInfiltration#557]
Currently, only the progress bar below the 3D geoscape icon indicates the remaining time.
When hovering over the 2D GUI icon, it should probably show remaining days/hours.

**Comment by Xymanek** [comment]
Easy to add here:
https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/061ad4e06c71d01541b6eefcfe0102e159a8fc00/CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc#L421-L442
