### ISSUE TITLE
Add "delay dark event" dummy reward to first dark event chain mission

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#568]
Multiple people have been confused with the dark event chain, so this should give some extra clarity. Plus, delaying the dark event is exactly what completing the first phase does!

**Comment by Xymanek** [comment]
> delaying the dark event is exactly what completing the first phase does

Conceptually... yeah. Technically? no. Technically the DE can't "resolve"/activate while the associated chain is up, regardless of how long the chain lasts

**Comment by cannonfodder1** [comment]
>Conceptually... yeah. Technically? no. Technically the DE can't "resolve"/activate while the associated chain is up, regardless of how long the chain lasts

In practice, that's how it works. Winning the first mission means the dark event won't trigger until the second wait period is over and the second mission expires.

**Comment by Xymanek** [comment]
Ok, let's do that since this detail is a bit more technical than we should expect players to know
