### ISSUE TITLE
Activity Chain to counter a dark event that is already triggered.

### ISSUE THREAD

**Issue by LordAbizi** [WOTCStrategyOverhaul/CovertInfiltration#576]
After a Dark Event already triggered I got an activity chain to counter it. I attach a save file from when the first mission in this chain appeared, and my mod list.
[overall.txt]
[save of first mission.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/5142291/save.of.first.mission.zip)

**Comment by Xymanek** [comment]
The mod list didn't get attached properly

**Comment by LordAbizi** [comment]
[overall.txt](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/5143222/overall.txt)
I hope now it works.  (also, if the appearance of three highlanders in that mod list looks suspicious, this is only an artifact of how AML works, I can guarantee that I'm not subscribed to other highlanders, and they are not installed).

**Comment by Xymanek** [comment]
Currently the [Grim Horizon Fix](https://steamcommunity.com/sharedfiles/filedetails/?id=2078307522&searchtext=XComGameState_HeadquartersAlien) mod is breaking https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/596
