### ISSUE TITLE
Avenger Crew size configuration/bigger size

### ISSUE THREAD

**Issue by ironhandjustice** [WOTCStrategyOverhaul/CovertInfiltration#577]
Hi,

I've been playing the mod for a while, along with a ton of other mods, and i've found a tiny limitation of infiltration mod.

Would be possible to add additional crew space (level 3/4) for the crew or, at least, a config value in the ini files (both imcrease cost and crewmen) to alter it?

In my case, I've a lot of different classes with a ultra-specific role, and I feel level 2 is short in high difficult levels. For example, I can't play on commander due enemy escaltion (bio viper mod is horrible causing wounds), and additional crewmen would save my life.

Is possible to add level 3 and 4 with high resources cost, or add values in ini file to alter them?

Thanks in advance and congrats for this awesome mod family.

**Comment by Xymanek** [comment]
The values (cost and space increase amount) for the current upgrades are all configurable in the `.ini`s.

Additional upgrades will not be added in the mod itself, at least before the release
