### ISSUE TITLE
[Investigate] Tutorials in XCOM Archives

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#582]
https://www.youtube.com/watch?v=onQwJeJxtc8&lc=Ugygui7-zMplJuD05Lh4AaABAg.9EMEC_dQNam9EMOs4US4Ux

* Should they be available to read before they are triggered?
* What happens if the tutorial system is disabled?

**Comment by cannonfodder1** [comment]
> * Should they be available to read before they are triggered?
> 
> * What happens if the tutorial system is disabled?

I think the archives should be a constant resource, no matter where a player is in the campaign or if they have the tutorials turned on or off.

**Comment by Xymanek** [comment]
In that case I think it will be easiest to just duplicate the entries/loc in the encyclopedia config. It's a bit of a manual work, but probably the simplest approach

**Comment by Xymanek** [comment]
Having considered this for a while, here are my thoughts:

* Generate the encyclopedia templates semi-automatically (make a helper that takes ID + title + body). Will need a CHL PR to un-private the loc variables in the templates, but that's easy, and avoids having to copy-paste the loc
* If tutorials are enabled: hide entries until the player has seen them normally (to avoid overwhelming/spoiling if the player checks the archives before seeing all tutorials)
* If tutorials are disabled: show all always
* Add a "welcome tutorial" (excluded from archives) which will popup when the player first sees the avenger view and will tell the player to carefully read the tutorials + that they are always in the archives + that the tutorials assume the default config and do not adjust

What I'm less sure about are the tactical tutorials - at the moment we have 2 (`SupplyExtract` and `AvatarCapture`). We can do the same thing with them but the archives are only accessible in strategy - it will still be useful when preparing for a mission but not during the mission (when it's most relevant)

**Comment by cannonfodder1** [comment]
> What I'm less sure about are the tactical tutorials - at the moment we have 2 (SupplyExtract and AvatarCapture). We can do the same thing with them but the archives are only accessible in strategy - it will still be useful when preparing for a mission but not during the mission (when it's most relevant)

We could add a commander ability button to show the tutorial, or a button in the pause menu. But that seems overkill for two tactical tutorials which serve to communicate small, easy to remember changes from vanilla.

**Comment by Xymanek** [comment]
That is definitely an overkill and requires additional, different type of logic/approach which I'm not willing to invest into such a small matter
