### ISSUE TITLE
Infil size upgrades do not prevent "no squad upgrades" achivement

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#586]
> winning with CI gives you the achievement for never buying squad size upgrades

https://discordapp.com/channels/578606792448409610/639765230569783320/765569354699112448

**Comment by Xymanek** [comment]
Requires CHL hook in `X2AchievementTracker`:

```cs
static function FinalMissionOnSuccess()
{

// ...

	if (!class'X2StrategyGameRulesetDataStructures'.static.HasSquadSizeUpgrade()) // Beat the game on Classic+ difficulty without buying a Squad Size upgrade
	{
		`ONLINEEVENTMGR.UnlockAchievement(AT_WinGameClassicWithoutBuyingUpgrade);
	}
```

**Comment by cannonfodder1** [comment]
I wonder, could we change something once the player enters the final mission to make `HasSquadSizeUpgrade()` in `X2StrategyGameRulesetDataStructures` return true? That would preclude the need for a highlander hook.

**Comment by Xymanek** [comment]
We could force-grant the squad size unlocks but that seems a very roundabout way compared to adding a very simple CHL event
