### ISSUE TITLE
Low POI options early game + delayed BM

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#587]
See discord discussion:

https://discordapp.com/channels/578606792448409610/639832893211934721/765232366104084530

**Comment by cannonfodder1** [comment]
As discussed on Discord, the solutions to these problems will be a 20-day one-time CA to reveal the Black Market, available from the start of the game, and another CA to spawn 2-3 POIs added to the monthly CA pool.

**Comment by cannonfodder1** [comment]
PR was merged locally, closing this issue
