### ISSUE TITLE
Redesign retaliation rewards and penalties

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#588]
Rescuing civilians from retaliations shouldn't grant any income rewards, it doesn't make any thematic sense. There needs to be something to replace that, however. We can pick option 1, option 2, both options, or think up something entirely different.

Option 1: each civilian rescued increases your influence with the associated faction. Ties in to the proposed faction influence rework (https://discordapp.com/channels/578606792448409610/639832893211934721/672242864276766726)

Option 2: each civilian killed decreases region income temporarily. Ties in to the proposed heat system for generating retals (https://discordapp.com/channels/578606792448409610/639832893211934721/669466128006774785)

**Comment by cannonfodder1** [comment]
Updated main issue description

**Comment by Xymanek** [comment]
> each civilian killed decreases region income temporarily

An alternative approach for this (without introducing new mechanics) would be to spawn a "Restore Resistance Infrastructure" CA. The CA would have a long expiration to allow for player choice, something like 10 days. The duration should probably scale with the amount of income lost but should be shorter than the "increase region income" CA.

**Comment by Xymanek** [comment]
Mod is released, so no major redesign will be happening
