### ISSUE TITLE
Intel POI check yield/time ratio compared to reaper HQ

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#594]
Possible "uselessness" noted by DerAva: https://youtu.be/qEsVxqkQsF4?t=2212

**Comment by cannonfodder1** [comment]
Every 2 days of scanning at the Reaper HQ, you gain 6 intel on average.
Every 11.5 days of scanning on average at an intel POI, you gain 40 intel on average.

HQ: 6/2 = 3 intel per day
POI: 40/11.5 = 3.5 ish intel per day

I think we could bump the intel POI's reward amount up to 60 or something, it's only barely better than the Reaper HQ.

**Comment by Xymanek** [comment]
Assuming vanilla POIs are ~6 days, it's 40/6=6.(6) intel per day, 2.(2) times higher than the HQ.

If we want to keep the vanilla ratio, the POI should yield ~75 intel.

Alternatively, we could look into setting individual timers per POI

**Comment by cannonfodder1** [comment]
I've upped the reward scalar from 0.5 to 1.0, meaning the intel per day comparison is ~7 for the POI and 3 for the HQ. A bit better than in vanilla, but I think that's warranted given the rewards available from scanning elsewhere, which are usually more sought after than intel.
