### ISSUE TITLE
Adjust GTS training slot

### ISSUE THREAD

**Issue by ChrisTheThinMint** [WOTCStrategyOverhaul/CovertInfiltration#595]
Based on discord discussion: https://discordapp.com/channels/578606792448409610/639832893211934721/767798220247924766

Training times are currently overtuned and make soldier deployment significantly more difficult.
Suggested changes:
- Remove time increase for rookie to squaddie promotion
- Reduce time for higher rank promotions slightly
```
; New GTS training values
ACADEMY_HOURS_PER_RANK=144 ; 6 days
+ACADEMY_DURATION_MODS=(Difficulty=3, Multiplier=2) ; Double on legend
+ACADEMY_DURATION_MODS=(PrePromotionRank=1, AdditionalHours=-24) ; -1 day for squaddie to corporal promotion
+ACADEMY_DURATION_MODS=(PrePromotionRank=2, AdditionalHours=-24) ; -1 day for corporal to sergeant promotion
+ACADEMY_DURATION_MODS=(PrePromotionRank=3, AdditionalHours=-24) ; -1 day for sergeant to lieutenant promotion
```
- Change the slot to promote soldiers to the next available rank instead of training to promote to the highest rank possible
- Add another GTS purchase for +1 training rank? DerAva wondered if one exists (it doesn't) and i think it would be a good idea for mid-to-late game stability in modded campaigns without imbalancing the game too much. Id make it require Major rank and something like 200-250 supplies

**Comment by ejaya2** [comment]
I was just going to mention re your last bullet point, the GTS purchase does stack with the live fire training continent bonus, so you can promote to Lieutenant. Being able to promote a rookie to Captain feels too strong in that case.

**Comment by ChrisTheThinMint** [comment]
I thought we adjusted Live Fire Training to only increase the GTS training rank by one?

**Comment by ejaya2** [comment]
Not sure, my campaign I started on 3.2 allows me to train LTs after getting Live Fire bonus and the GTS rank upgrade.
