### ISSUE TITLE
Clarify that 1 free TLP item is intended

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#597]
e.g. DerAva thought that it was a bug from some mod combination.

Should probably mention the related POIs

**Comment by Xymanek** [comment]
Should also mention that removing/swapping weapon attachments is enabled by default

**Comment by cannonfodder1** [comment]
![20210305144554_1](https://user-images.githubusercontent.com/1369684/110182897-8dbc7e00-7dc2-11eb-8704-fe5c6eaadacd.jpg)

**Comment by Xymanek** [comment]
The last point should include "by default" since PA has an MCM option to disable that change (see https://github.com/WOTCStrategyOverhaul/PrototypeArmoury/blob/b381506c0b870ae1ad89ea84c1d14d5c7e97c0e6/PrototypeArmoury/Localization/PrototypeArmoury.int#L11)

**Comment by cannonfodder1** [comment]
```Additionally, instead of gaining a single Tactical Legacy Pack weapon or armour when the schematic is built, a 'prototype' is granted when the relevant research is completed. Additional prototypes can be gained from certain scanning sites.

By default, weapon attachments can be freely removed and transferred. The 'Remove Weapon Upgrades' button on the squad select screen removes upgrades from all weapons not equipped by the current squad. In the weapon upgrade screen, the corresponding button removes all upgrades from the currently selected weapon.```

**Comment by Xymanek** [comment]
Looks good
