### ISSUE TITLE
CDE A1 is almost always monument

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#606]
https://discordapp.com/channels/578606792448409610/639832893211934721/769450941194960898

**Comment by cannonfodder1** [comment]
Looks like the MissionFamilies card deck is populated in XComTacticalMissionManager. Maybe switch the spawning system to use mission types instead? Then the mission families with more variety in them will be spawned more often than the families with only one mission type (like sabotage monument).
