### ISSUE TITLE
Infil in ActivityChain_DestroyFacility can spawn not yet met chosen

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#609]
Discord report: https://discordapp.com/channels/578606792448409610/639765230569783320/771650205946085389

`ActivityChain_DestroyFacility` spawns in a region with the facility, which can be not yet contacted, hence the associated chosen can be not yet met. Should we force disable the chosen in this case?

**NOTE**: issue needs to be validated

**Comment by cannonfodder1** [comment]
An alternative solution would simply be to make `ActivityChain_DestroyFacility` spawn only in contacted regions. It was originally envisioned as connected to the region's facility, but that doesn't make sense anymore with the facility lead overhaul.

**Comment by Xymanek** [comment]
A middle ground option would be to finally make use of `XCGS_AC::SecondaryRegionRef` and have the CA spawn in the facility region but infil in a contacted (potentially different) one

**Comment by cannonfodder1** [comment]
I don't like having different parts of a chain happen in different regions, it makes it easier to track what chains are where when everything is in one spot. If you don't have any objections, I think I'll go with making the chain restricted to relay'd regions.

**Comment by Xymanek** [comment]
Go ahead then
