### ISSUE TITLE
"Irrelevant Item" is a bit overzealous

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#612]
https://youtu.be/Hh6bR7VnlV4?t=5203
![image](https://user-images.githubusercontent.com/2865341/98703415-20ed2600-2384-11eb-88cb-e95a311c9c92.png)

Possibly add a check for whether the item can be unequipped or not?

**Comment by cannonfodder1** [comment]
> Possibly add a check for whether the item can be unequipped or not?

I don't think that's necessary. The warning in the screenshot is completely unintended, it shouldn't be showing on infinite items like grenades.

**Comment by cannonfodder1** [comment]
I retract my previous statement, I've confirmed that this bug occurs because of the pistol, not the grenades.
