### ISSUE TITLE
Only a single Counter DE chain spawns at the start of the month

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#614]
When there are 3 non-chosen dark events, and the player has 4 regions, only one counter dark event chain is appearing. Occurs here: https://youtu.be/oTlWpByGU4U?t=4840

Requires investigation and bugfix using the save provided.
[save_47_1.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/5576785/save_47_1.zip)

**Comment by Xymanek** [comment]
Possibly related to #576
