### ISSUE TITLE
Make covert actions for missions we want to be infiltratable

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#63]
+ narratives and cosmetic rewards so that the ui isn't empty

**Comment by cannonfodder1** [comment]
For P1 missions, the cosmetic reward will be tied to the two P2 mission options you get afterwards. One will be random and the other will be in the category of the cosmetic reward.

- "Dark Event Counteroperation" = counter a random DE
- "Critical Personnel Recovery" = engineer/scientist rescue
- "Materiel Recovery" = smash n grab or supply raid
etc etc
