### ISSUE TITLE
Lessen crew limit pressure on non-soldiers in the late game

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#630]
The best way to do this was discussed and we think that the Workshop should disable Engineers counting towards the limit and Laboratory disable scientists from counting. The crew limit has always been a mechanism to limit soldiers and we don't want the player to feel forced to dismiss soldiers in late game to make room for staff.

**Comment by Xymanek** [comment]
It would be also a good idea to mention this in the tutorial popup

**Comment by cannonfodder1** [comment]
> It would be also a good idea to mention this in the tutorial popup

Yup, now that the actual mechanics have changed on the LS repo I'll leave this issue open until that's addressed
