### ISSUE TITLE
Infiltrating status doesn't show up in armory

### ISSUE THREAD

**Issue by Xymanek** [WOTCStrategyOverhaul/CovertInfiltration#66]
Just empty space. Figure out why

**Comment by robojumper** [comment]
Reposting from Discord:

https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/beea406cf3216275a641bcac9adfe22b4c6baba4/CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_StaffSlots_Infiltration.uc#L157 should (additionally?) be GetBonusDisplayStringFn
