### ISSUE TITLE
Bugged Supply Raid

### ISSUE THREAD

**Issue by Crazy-eyed1** [WOTCStrategyOverhaul/CovertInfiltration#662]
I sent out a team to prepare a supply raid and the supply raid mission spawned as a chosen avenger assault. 
[save_AUTOSAVE- Campaign 1, Mission 26_1.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/6746383/save_AUTOSAVE-.Campaign.1.Mission.26_1.zip)

**Comment by Xymanek** [comment]
Mission was spawned by another mod (following the completion of `CoverAction_PrepareRaid`)
