### ISSUE TITLE
Sabotage monument cannot be completed if charges are placed before map is clear

### ISSUE THREAD

**Issue by cannonfodder1** [WOTCStrategyOverhaul/CovertInfiltration#668]
> found a bug. mission destroy monument. When you activate the x4 charges before you killed all advents, the mission turns the fullfilled charge event back to "has to be done" . the green marker for placing he x4 charge is then missing and you cannot win the mission.

**Comment by Xymanek** [comment]
![image](https://user-images.githubusercontent.com/2865341/128844220-380d716f-589b-46c4-bdbf-e7174a60bd6b.png)
![image](https://user-images.githubusercontent.com/2865341/128844260-5604484b-aab5-4738-99d8-1ad21708f942.png)

**Comment by cannonfodder1** [comment]
Issue cannot be reproduced.
