### ISSUE TITLE
Cost slots and build items shortcut interaction

### ISSUE THREAD

**Issue by Crazy-eyed1** [WOTCStrategyOverhaul/CovertInfiltration#698]
If the player allocates supplies to negate a risk the supplies are not immediately spent. So that player is then able to go into engineering, from the build items button, to build items and if they spend supplies after allocating them to negate the risk down to an amount of supplies lower than that which is required for the risk reduction the allocate resources UI button as well as the confirm Covert Action button both get greyed out. Preventing the player from launching the covert action.

https://youtu.be/DuWr6DLnZE0

**Comment by Xymanek** [comment]
Unafforardble slots are cleared currently only when entering the loadout, not when coming back from the build items shortcut

https://github.com/WOTCStrategyOverhaul/CovertInfiltration/blob/c923cd266f382c55dd099d08bc235671a1bd25a1/CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc#L1398-L1407

**Comment by Xymanek** [comment]
See PR for nuances with the fix
